<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rnc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>RelaxNG Compact</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\bgrammar\b</string>
			<key>name</key>
			<string>keyword.other.grammar.rnc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstart\b</string>
			<key>name</key>
			<string>keyword.other.start.rnc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(text|empty|xsd\:(int|integer|double|date(Time)?|time|string|decimal))\b</string>
			<key>name</key>
			<string>storage.type.rnc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.attribute.rnc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute.rnc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(attribute)\s+([a-zA-Z][a-zA-Z_0-9]*)\s*\{</string>
			<key>name</key>
			<string>meta.declaration.attribute.rnc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.element.rnc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.element.rnc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(element)\s+([a-zA-Z][a-zA-Z_0-9]*)\s*\{</string>
			<key>name</key>
			<string>meta.declaration.element.rnc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.hash.rnc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.rnc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rnc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.rnc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rnc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.grammar_production.rnc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z][a-zA-Z_0-9]*)\s*=</string>
			<key>name</key>
			<string>meta.grammar_production.rnc</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.rnc</string>
	<key>uuid</key>
	<string>85F32571-780F-4AAC-BA70-C2229E0B1BDA</string>
</dict>
</plist>
