<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bmx</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?xi)
	^\s*(
		(?&lt;!end|end\s)(function|method|type|select|while|extern|try|if|rem) |
		for | repeat | '\#region
	)\b</string>
	<key>foldingStopMarker</key>
	<string>(?xi)
	^\s*(
	# end &lt;keyword&gt;
		end\s*(function|method|type|select|while|extern|if|try|rem) |
		wend | until | forever | next | '\#end\s?region
	)\b</string>
	<key>keyEquivalent</key>
	<string>^~B</string>
	<key>name</key>
	<string>BlitzMax</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>punctuation.terminator.statement.blitzmax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.apostrophe.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#url_content</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\b(?&lt;!end|end\s)rem\b</string>
			<key>end</key>
			<string>(?i)\bend\s?rem\b</string>
			<key>name</key>
			<string>comment.block.rem.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#url_content</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\b(?:(local)|(global))\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.variable.local.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.global.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(.(?=[='])|$)</string>
			<key>name</key>
			<string>meta.variable.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_]\w*</string>
					<key>name</key>
					<string>variable.other.blitzmax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.constant.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.blitzmax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(const)\s+([a-zA-Z_]\w*)</string>
			<key>name</key>
			<string>meta.constant.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bptr\b</string>
			<key>name</key>
			<string>storage.modifier.variable.pointer.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bvar\b</string>
			<key>name</key>
			<string>storage.modifier.variable.reference.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^\s*\?(not\s+)?\w*</string>
			<key>name</key>
			<string>keyword.control.preprocessor.blitzmax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.attributes.braces.blitzmax</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>storage.modifier.attributes.blitzmax</string>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.attributes.braces.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.attributes.blitzmax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(?:(?:^|;)\s*)(try)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.try.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)\b(end\s?try)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.try.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.try.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)^\s*(catch)</string>
					<key>name</key>
					<string>keyword.control.try.catch.blitzmax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(?:(?:^|;)\s*)(extern)(?:\s+((")[^"]*("))|\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.extern.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.blitzmax</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.blitzmax</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(?:(?:^|;)\s*)\b(end\s?extern)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.extern.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.extern.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\b(global)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.variable.global.extern.blitzmax</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*(.(?=[='])|$)</string>
					<key>name</key>
					<string>meta.variable.blitzmax</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[a-zA-Z_]\w*</string>
							<key>name</key>
							<string>variable.other.blitzmax</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.extern.blitzmax</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.extern.blitzmax</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(?:(?:^|;)\s*)(function)\s+([a-zA-Z_]\w*)\b</string>
					<key>name</key>
					<string>meta.function.extern.blitzmax</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)(?:(?:^|;)\s*)(type)\s+([a-zA-Z_]\w*)(?:\s+(extends)\s+([a-zA-Z_]\w*))?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.extern.blitzmax</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.extern.blitzmax</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.extends.extern.blitzmax</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.extern.blitzmax</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?i)\b(end\s?type)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.extern.blitzmax</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.type.extern.blitzmax</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.method.method.extern.blitzmax</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.method.extern.blitzmax</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i)(?:(?:^|;)\s*)(method)\s+([a-zA-Z_]\w*)\b</string>
							<key>name</key>
							<string>meta.method.blitzmax</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(?:(?:^|;)\s*)(function)\s+([a-zA-Z_]\w*)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)\b(end\s?function)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.module.blitzmax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(import)\s+((?:[a-zA-Z_]\w*\.?)+)</string>
			<key>name</key>
			<string>meta.import.module.blitzmax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\b(import)\s+(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.blitzmax</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.double.blitzmax</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.import.file.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_content</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.framework.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.module.blitzmax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(framework)\s+((?:[a-zA-Z_]\w*\.?)+)</string>
			<key>name</key>
			<string>meta.framework.blitzmax</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.module.blitzmax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(module)\s+(([a-zA-Z_]\w*\.?)+)</string>
			<key>name</key>
			<string>meta.module.blitzmax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\b(include)\s+(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.include.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.blitzmax</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.double.blitzmax</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.include.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_content</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\b(incbin)\s+(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.incbin.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.blitzmax</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.double.blitzmax</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.incbin.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_content</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\b(moduleinfo)\s+(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.moduleinfo.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.blitzmax</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.double.blitzmax</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.moduleinfo.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_content</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(?:(?:^|;)\s*)(type)\s+([a-zA-Z_]\w*)(?:\s+(extends)\s+([a-zA-Z_]\w*))?(?:\s+(final|abstract))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.blitzmax</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extends.blitzmax</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.blitzmax</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.class.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)\b(end\s?type)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.type.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(?:(?:^|;)\s*)(method)\s+([a-zA-Z_]\w*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.method.blitzmax</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.method.blitzmax</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?i)(?:\)\s+(abstract)\s*)$|\b(end\s?method)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.abstract.blitzmax</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.method.blitzmax</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.method.blitzmax</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)\bfinal\b</string>
							<key>name</key>
							<string>storage.modifier.method.final.blitzmax</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(field)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.variable.field.blitzmax</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*(.(?=[='])|$)</string>
					<key>name</key>
					<string>meta.variable.field.blitzmax</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[a-zA-Z_]\w*</string>
							<key>name</key>
							<string>variable.other.blitzmax</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b((end\s?|else\s?)?(if)|else|then)\b</string>
			<key>name</key>
			<string>keyword.control.if.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(exit|continue)\b</string>
			<key>name</key>
			<string>keyword.control.loop.blitzmax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(?:(?:^|;)\s*)(while)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.while.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(?:(?:^|;)\s*)(end\s?while|wend)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.while.end.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.control.while.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(?:(?:^|;)\s*)(for)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.for.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(?:(?:^|;)\s*)(next)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.for.end.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.control.for.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\beachin\b</string>
					<key>name</key>
					<string>keyword.control.for.eachin.blitzmax</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\bto\b</string>
					<key>name</key>
					<string>keyword.control.for.to.blitzmax</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\buntil\b</string>
					<key>name</key>
					<string>keyword.control.for.until.blitzmax</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\bstep\b</string>
					<key>name</key>
					<string>keyword.control.for.step.blitzmax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(?:(?:^|;)\s*)(repeat)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.repeat.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(?:(?:^|;)\s*)(until|forever)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.repeat.end.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.control.repeat.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(?:(?:^|;)\s*)(select)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.select.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(?:(?:^|;)\s*)(end\s?select)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.select.end.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.control.select.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.select.case.blitzmax</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(?:(?:^|;)\s*)(case)\b</string>
					<key>name</key>
					<string>meta.control.select.case.blitzmax</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.select.default.blitzmax</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(?:(?:^|;)\s*)(default)\b</string>
					<key>name</key>
					<string>meta.control.select.default.blitzmax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(mod|shr|shl|sar|and|or|not)\b</string>
			<key>name</key>
			<string>keyword.operator.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:?[\^+\-=&amp;|&gt;&lt;]</string>
			<key>name</key>
			<string>keyword.operator.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(object|string|byte|short|int|long|float|double)\b</string>
			<key>name</key>
			<string>storage.type.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(private|public)\b</string>
			<key>name</key>
			<string>keyword.other.scope.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\breturn\b</string>
			<key>name</key>
			<string>keyword.control.return.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(strict|superstrict)\b</string>
			<key>name</key>
			<string>keyword.other.strictness.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bpi\b</string>
			<key>name</key>
			<string>constant.language.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bnull\b</string>
			<key>name</key>
			<string>constant.language.null.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.boolean.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$[0-9a-fA-F]{1,16})</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\%[01]{1,128})</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x) (?&lt;! % | \$ ) (
			        \b ([0-9]+ \. [0-9]+) |
			        (\. [0-9]+)
			    )</string>
			<key>name</key>
			<string>constant.numeric.float.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)\b(([0-9]+))</string>
			<key>name</key>
			<string>constant.numeric.integer.blitzmax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_content</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(self)\b</string>
			<key>name</key>
			<string>variable.language.self.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(super)\b</string>
			<key>name</key>
			<string>variable.language.super.blitzmax</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.new.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.blitzmax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(new)\s+([a-zA-Z_]\w*)\b</string>
			<key>name</key>
			<string>meta.call.constructor.blitzmax</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.blitzmax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b\:(([a-zA-Z_]\w*)( (Ptr|Var))*)</string>
			<key>name</key>
			<string>meta.typename.blitzmax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.array.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.array.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.array.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>string_content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\~[0qnr~t]</string>
					<key>name</key>
					<string>constant.character.escape.blitzmax</string>
				</dict>
			</array>
		</dict>
		<key>url_content</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z_]\w*://\S*</string>
			<key>name</key>
			<string>meta.url.blitzmax</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.blitzmax</string>
	<key>uuid</key>
	<string>4BF45A32-1013-4E9B-979C-3CD5A20D81AD</string>
</dict>
</plist>
