<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>t2t</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>Txt2tags</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^%%%\s*$</string>
			<key>end</key>
			<string>^%%%\s*$\n?</string>
			<key>name</key>
			<string>comment.block.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*[_=-]{20,}\s*$\n?</string>
			<key>name</key>
			<string>string.unquoted.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>__([^\s](|.*?[^\s])_*)__</string>
			<key>name</key>
			<string>markup.underline.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*([^\s](|.*?[^\s])\**)\*\*</string>
			<key>name</key>
			<string>markup.bold.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*={1}[^=](|.*[^=])={1}(\[[\w-]*\])?\s*$\n?</string>
			<key>name</key>
			<string>markup.heading.1.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*={2}[^=](|.*[^=])={2}(\[[\w-]*\])?\s*$\n?</string>
			<key>name</key>
			<string>markup.heading.2.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*={3}[^=](|.*[^=])={3}(\[[\w-]*\])?\s*$\n?</string>
			<key>name</key>
			<string>markup.heading.3.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*={4}[^=](|.*[^=])={4}(\[[\w-]*\])?\s*$\n?</string>
			<key>name</key>
			<string>markup.heading.4.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*={5}[^=](|.*[^=])={5}(\[[\w-]*\])?\s*$\n?</string>
			<key>name</key>
			<string>markup.heading.5.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\+{1}[^+](|.*[^+])\+{1}(\[[\w-]*\])?\s*$\n?</string>
			<key>name</key>
			<string>markup.heading.1.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\+{2}[^+](|.*[^+])\+{2}(\[[\w-]*\])?\s*$\n?</string>
			<key>name</key>
			<string>markup.heading.2.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\+{3}[^+](|.*[^+])\+{3}(\[[\w-]*\])?\s*$\n?</string>
			<key>name</key>
			<string>markup.heading.3.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\+{4}[^+](|.*[^+])\+{4}(\[[\w-]*\])?\s*$\n?</string>
			<key>name</key>
			<string>markup.heading.4.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\+{5}[^+](|.*[^+])\+{5}(\[[\w-]*\])?\s*$\n?</string>
			<key>name</key>
			<string>markup.heading.5.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//([^\s](|.*?[^\s])/*)//</string>
			<key>name</key>
			<string>markup.italic.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>--([^\s](|.*?[^\s])-*)--</string>
			<key>name</key>
			<string>invalid.deprecated.strike.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>""([^\s](|.*?[^\s])"*)""</string>
			<key>name</key>
			<string>string.quoted.other.raw.inline.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^""" (?=.).*$\n?</string>
			<key>name</key>
			<string>string.quoted.other.raw.line.txt2tags</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^"""\s*$</string>
			<key>end</key>
			<string>^"""\s*$\n?</string>
			<key>name</key>
			<string>string.quoted.other.raw.block.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>''([^\s](|.*?[^\s])'*)''</string>
			<key>name</key>
			<string>string.quoted.other.tagged.inline.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^''' (?=.).*$\n?</string>
			<key>name</key>
			<string>string.quoted.other.tagged.line.txt2tags</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^'''\s*$</string>
			<key>end</key>
			<string>^'''\s*$\n?</string>
			<key>name</key>
			<string>string.quoted.other.tagged.block.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^ *\+ (?=[^ ])</string>
			<key>name</key>
			<string>markup.list.numbered.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^ *- (?=[^ ])</string>
			<key>name</key>
			<string>markup.list.unnumbered.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^ *: (?=.)</string>
			<key>name</key>
			<string>markup.list.unnumbered.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^( *)([-+:])\s*$</string>
			<key>name</key>
			<string>markup.list.txt2tags</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^```\s*$</string>
			<key>end</key>
			<string>^```\s*$\n?</string>
			<key>name</key>
			<string>markup.raw.verb.block.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^``` (?=.).*$\n?</string>
			<key>name</key>
			<string>markup.raw.verb.line.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>``([^\s](|.*?[^\s])`*)``</string>
			<key>name</key>
			<string>markup.raw.verb.inline.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s+$</string>
			<key>name</key>
			<string>invalid.deprecated.trailing-whitespace.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)%%(date|mtime|infile|outfile)(\(.*?\))?|%%toc</string>
			<key>name</key>
			<string>string.interpolated.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^%!\s*(target|encoding|style|options|include|includeconf|preproc|postproc|guicolors)\s*(\(\w*\))?\s*:.*</string>
			<key>name</key>
			<string>constant.character.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[[\w_,.+%$#@!?+~/-]+\.(png|jpe?g|gif|eps|bmp)\]</string>
			<key>name</key>
			<string>meta.tag.image.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b[A-Za-z0-9_.-]+@([A-Za-z0-9_-]+\.)+[A-Za-z]{2,4}\b(\?[A-Za-z0-9/%&amp;=+;.,$@*_-]+)?</string>
			<key>name</key>
			<string>meta.tag.email.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b((https?|ftp|news|telnet|gopher|wais)://([A-Za-z0-9_.-]+(:[^ @]*)?@)?|(www[23]?|ftp)\.)[A-Za-z0-9%._/~:,=$@&amp;+-]+\b/*(\?[A-Za-z0-9/%&amp;=+;.,$@*_-]+)?(#[A-Za-z0-9%._-]*)?</string>
			<key>name</key>
			<string>meta.tag.url.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\[(\[[\w_,.+%$#@!?+~/-]+\.(png|jpe?g|gif|eps|bmp)\]|[^]]+) (((https?|ftp|news|telnet|gopher|wais)://([A-Za-z0-9_.-]+(:[^ @]*)?@)?|(www[23]?|ftp)\.)[A-Za-z0-9%._/~:,=$@&amp;+-]+\b/*(\?[A-Za-z0-9/%&amp;=+;.,$@*_-]+)?(#[A-Za-z0-9%._-]*)?|[A-Za-z0-9_.-]+@([A-Za-z0-9_-]+\.)+[A-Za-z]{2,4}\b(\?[A-Za-z0-9/%&amp;=+;.,$@*_-]+)?|[A-Za-z0-9%._/~:,=$@&amp;+-]+|[A-Za-z0-9%._/~:,=$@&amp;+-]*(#[A-Za-z0-9%._-]*))\]</string>
			<key>name</key>
			<string>meta.tag.link.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\t.*$\n?</string>
			<key>name</key>
			<string>markup.quote.txt2tags</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^%.*$\n?</string>
			<key>name</key>
			<string>comment.line.txt2tags</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.txt2tags</string>
	<key>uuid</key>
	<string>B5A751C0-2CE4-41A5-99FB-7B673943DE60</string>
</dict>
</plist>
