<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>JavaScript Syntax: version 2.0 branched for bracket testing</string>
	<key>fileTypes</key>
	<array>
		<string>js</string>
		<string>htc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(^.*{[^}]*$|^.*\([^\)]*$|^.*/\*(?!.*\*/).*$)</string>
	<key>foldingStopMarker</key>
	<string>(^\s*\}|^\s*\)|^(?!.*/\*).*\*/)</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JavaScript + MochiKit Bracketed</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#conditional-compilation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#round-brackets</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#round-brackets1</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js.mochikit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?&lt;=var\s)\b[a-zA-Z]\w*\b|\b[a-zA-Z]\w*\b(?=(\[|\s*(&amp;|\*|\-\-|\-|\+\+|\+|~|===|==|=|!=|!==|&lt;=|&gt;=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|&lt;&gt;|&lt;|&gt;|!|&amp;&amp;|\|\||\?\:|\*=|/=|%=|\+=|\-=|&amp;=|\^=))))</string>
			<key>name</key>
			<string>variable.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>conditional-compilation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*(?=@)</string>
					<key>end</key>
					<string>(?&lt;=@)\*/</string>
					<key>name</key>
					<string>comment.block.conditional.js</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>@(if|elif|else|end)</string>
					<key>name</key>
					<string>keyword.control.conditional.js</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@(cc_on|set)</string>
					<key>name</key>
					<string>keyword.operator.conditional.js</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@(_win32|_win16|_mac|_alpha|_x86|_mc680x0|_PowerPC|_jscript_build|_jscript_version|_jscript|_debug|_fast|[a-zA-Z]\w+)</string>
					<key>name</key>
					<string>variable.conditional.js</string>
				</dict>
			</array>
		</dict>
		<key>round-brackets</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.group.braces.curly</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.group.braces.round</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.mochikit.bracketed</string>
	<key>uuid</key>
	<string>BDA3913D-957F-4AAD-AAC5-2F7BCDADF6BC</string>
</dict>
</plist>
