<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>MochiKit JavaScript Syntax: importing the normal JavaScript Syntax</string>
	<key>fileTypes</key>
	<array>
		<string>js</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(^.*{[^}]*$|^.*\([^\)]*$|^.*/\*(?!.*\*/).*$)</string>
	<key>foldingStopMarker</key>
	<string>(^\s*\}|^\s*\)|^(?!.*/\*).*\*/)</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JavaScript + MochiKit</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(\$|getElement|addElementClass|addLoadEvent|addToCallStack|appendChildNodes|computedStyle|currentDocument|currentWindow|elementDimensions|elementPosition|emitHTML|escapeHTML|focusOnLoad|formContents|getElement|getElementsByTagAndClassName|getNodeAttribute|hasElementClass|hideElement|registerDOMConverter|removeElement|removeElementClass|replaceChildNodes|scrapeText|setDisplayForElement|setElementClass|setNodeAttribute|showElement|swapDOM|swapElementClass|toggleElementClass|toHTML|updateNodeAttributes|withWindow|withDocument)(?=\()</string>
			<key>name</key>
			<string>support.function.js.mochikit.dom</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(createDOM|A|BUTTON|BR|CANVAS|DIV|FIELDSET|FORM|H1|H2|H3|HR|IMG|INPUT|LABEL|LEGEND|LI|OL|OPTGROUP|OPTION|P|PRE|SELECT|SPAN|STRONG|TABLE|TBODY|TD|TEXTAREA|TFOOT|TH|THEAD|TR|TT|UL|createDOMFunc)(?=\()</string>
			<key>name</key>
			<string>support.function.js.mochikit.dom.createdom</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict/>
	<key>scopeName</key>
	<string>source.js.mochikit</string>
	<key>uuid</key>
	<string>3D67C260-4654-4C0F-9729-0BF54A9FE03B</string>
</dict>
</plist>
