<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dist</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
	<key>name</key>
	<string>Installer Distribution Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;(script)&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/(script)&gt;)</string>
			<key>name</key>
			<string>source.embedded.js.apple-dist</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bsystem\b</string>
					<key>end</key>
					<string>(?=(\(|\s))|$</string>
					<key>name</key>
					<string>support.class</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(compareVersions|defaults|gestalt|localizedString(WithFormat)?|localizedStandardString(WithFormat)?|log|propertiesOf|run(Once)?|sysctl|users\.desktopSessionsCount|version)\b</string>
							<key>name</key>
							<string>support.function</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(applications)\b</string>
							<key>end</key>
							<string>(?=(\(|\s))|$</string>
							<key>name</key>
							<string>support.function</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\b(fromPID|fromIdentifier|all)\b</string>
									<key>name</key>
									<string>support.variable</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(files)\b</string>
							<key>end</key>
							<string>(?=(\(|\s))|$</string>
							<key>name</key>
							<string>support.function</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\b(fileExistsAtPath|plistAtPath|bundleAtPath)\b</string>
									<key>name</key>
									<string>support.variable</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(ioregistry)\b</string>
							<key>end</key>
							<string>(?=(\(|\s))|$</string>
							<key>name</key>
							<string>support.function</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\b(fromPath|matching(Class|Name)|(children|parents)Of)\b</string>
									<key>name</key>
									<string>support.variable</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(choices)\b</string>
					<key>end</key>
					<string>(?=(\(|\s))|$</string>
					<key>name</key>
					<string>support.class</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(.*)\.(bundle|customLocation(AllowAlternateVolumes)?|description(-mime-type)?|(start_)?enabled|id|(start_)?selected|tooltip|(start_)?visible|title|packages|packageUpgradeAction)\b</string>
							<key>name</key>
							<string>support.variable</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\bmy\b</string>
					<key>end</key>
					<string>(?=(\(|\s))|$</string>
					<key>name</key>
					<string>support.class</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\b(choice)\b</string>
							<key>end</key>
							<string>(?=(\(|\s))|$</string>
							<key>name</key>
							<string>support.function</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\b(bundle|customLocation(AllowAlternateVolumes)?|description(-mime-type)?|(start_)?enabled|id|(start_)?selected|tooltip|(start_)?visible|title|packages|packageUpgradeAction)\b</string>
									<key>name</key>
									<string>support.variable</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(result)\b</string>
							<key>end</key>
							<string>(?=(\(|\s))|$</string>
							<key>name</key>
							<string>support.function</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\b(type|title|message)\b</string>
									<key>name</key>
									<string>support.variable</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(target)\b</string>
							<key>end</key>
							<string>(?=(\(|\s))|$</string>
							<key>name</key>
							<string>support.function</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\b(mountpoint|availableKilobytes|systemVersion|receiptForIdentifier)\b</string>
									<key>name</key>
									<string>support.variable</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.xml.apple-dist</string>
	<key>uuid</key>
	<string>25D29CD3-07B7-44C6-A96A-46CF771130EB</string>
</dict>
</plist>
