<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>Snw</string>
		<string>Rnw</string>
		<string>snw</string>
		<string>rnw</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^&lt;&lt;(.?*)&gt;&gt;=|\\begin\{.*\}</string>
	<key>foldingStopMarker</key>
	<string>^@(.?*)$|\\end\{.*\}</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>SWeave</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(&lt;&lt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.sweave</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;&gt;)(?==)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.sweave</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.parameters.sweave</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.name-of-parameter.sweave</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.sweave</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.sweave</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language.results.sweave</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.label.sweave</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w+)(=)(?:(true|false)|(verbatim|tex|hide)|([\w.]+))</string>
					<key>name</key>
					<string>meta.parameter.sweave</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\w.]+</string>
					<key>name</key>
					<string>string.unquoted.label.sweave</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.parameters.sweave</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=&gt;&gt;)(=)(.*)\n</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.sweave</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.other.sweave</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.r.embedded.sweave</string>
			<key>end</key>
			<string>^(@)(.*)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.sweave</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.other.sweave</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.code.sweave</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s+@.*\n?</string>
					<key>name</key>
					<string>invalid.illegal.sweave</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.r</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s+&lt;&lt;.*\n?</string>
			<key>name</key>
			<string>invalid.illegal.sweave</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\\begin(\{)Scode(\})</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.latex</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.r.embedded.sweave</string>
			<key>end</key>
			<string>^\\end(\{)Scode(\})</string>
			<key>name</key>
			<string>meta.block.source.r</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.r</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\\Sexpr(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.latex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.r.embedded.sweave</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.r</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.latex.sweave</string>
	<key>uuid</key>
	<string>1F450973-8259-4BA2-A754-48C634561A13</string>
</dict>
</plist>
