<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>foldingStartMarker</key>
	<string>%\s*region \w*</string>
	<key>foldingStopMarker</key>
	<string>%\s*end(\s*region)?</string>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>Prolog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.prolog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.prolog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>''</string>
					<key>name</key>
					<string>constant.character.escape.quote.prolog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.prolog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.prolog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.prolog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(%).*$\n?</string>
			<key>name</key>
			<string>comment.line.percentage.prolog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:-</string>
			<key>name</key>
			<string>keyword.operator.definition.prolog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>variable.other.prolog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
			I changed this from entity to storage.type, but have no idea what it is -- Allan
			And I changed this to constant.other.symbol after glancing over the docs,
			    might still be wrong.  -- Infininight
			</string>
			<key>match</key>
			<string>\b[a-z][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>constant.other.symbol.prolog</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.prolog</string>
	<key>uuid</key>
	<string>C0E2ADB0-1706-4A28-8DB7-263BDC8B5C5C</string>
</dict>
</plist>
