<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>k</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{.*\n?</string>
	<key>foldingStopMarker</key>
	<string>}</string>
	<key>keyEquivalent</key>
	<string>^~K</string>
	<key>name</key>
	<string>K</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(\_d|\_v|\_t|\_h|\_p|\_i|\_w|\_u|\_n|\_f)\b</string>
			<key>name</key>
			<string>variable.language.system.k</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.k</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.k</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.untitled.k</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled.k</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\_bin|\_di|\_dv|\_draw|\_gtime|\_ic|\_jd|\_lsq|\_dot|\_mul|\_inv|\_in|\_sv|\_sm|\_sm|\_ss|\_ssr|\_vs)\b</string>
			<key>name</key>
			<string>support.function.system.k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\_abs|\_floor|\_sin|\_sin|\_cos|\_tan|\_sinh|\_cosh|\_tanh|\_exp|\_log|\_sqr|\_sqrt)\b</string>
			<key>name</key>
			<string>support.function.system.k</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.symbol.k</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((\`)[a-zA-Z_]\w+)\b</string>
			<key>name</key>
			<string>entity.name.tag.k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\~|\!|\@|\#|\$|\%|\^|\&amp;|\*|\_|\+|\-|\=|\||\|.\/|\?|\.|\&lt;|\&gt;|'|,|:|`</string>
			<key>name</key>
			<string>keyword.operator.k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\d:)</string>
			<key>name</key>
			<string>support.function.io.k</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.k</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^[\s]+(/).*$\n?)|(^(/).*$\n?)</string>
			<key>name</key>
			<string>comment.line.slash.k</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.k</string>
	<key>uuid</key>
	<string>9F8DA629-A8F8-4D6B-81F7-12804FFE7476</string>
</dict>
</plist>
