<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfdg</string>
	</array>
	<key>foldingStartMarker</key>
	<string>[\{\[]\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*[\}\]]</string>
	<key>keyEquivalent</key>
	<string>^~F</string>
	<key>name</key>
	<string>Context Free</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#startshape-directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#include-directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#background-directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rule-directive</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>background-directive</key>
		<dict>
			<key>begin</key>
			<string>\b(background)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.background.cfdg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})|(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.unordered-block.end.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.ordered-block.end.cfdg</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#color-adjustment-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>color-adjustment</key>
		<dict>
			<key>match</key>
			<string>\||\b(h(ue)?|sat(uration)?|b(rightness)?|a(lpha)?)\b</string>
			<key>name</key>
			<string>constant.language.color-adjustment.cfdg</string>
		</dict>
		<key>color-adjustment-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.unordered-block.begin.cfdg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#color-adjustment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.ordered-block.begin.cfdg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#color-adjustment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(//|#)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.cfdg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n</string>
					<key>name</key>
					<string>comment.line.cfdg</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(/\*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.comment.begin.cfdg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\*/)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.comment.end.cfdg</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.cfdg</string>
				</dict>
			</array>
		</dict>
		<key>geometry-adjustment</key>
		<dict>
			<key>match</key>
			<string>\b(x|y|z|s(ize)?|r(ot(ate)?)?|f(lip)?|skew)\b</string>
			<key>name</key>
			<string>constant.language.geometry-adjustment.cfdg</string>
		</dict>
		<key>include-directive</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.include.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.file-name.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(include)\s++(\S++)</string>
		</dict>
		<key>loop</key>
		<dict>
			<key>begin</key>
			<string>(\d++)\s*+(\*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.loop.cfdg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})|(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.unordered-block.end.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.ordered-block.end.cfdg</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#shape-adjustment-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.sign.cfdg</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.integer-float.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\+|\-)?((\d++)?(\.))?\d++</string>
			<key>name</key>
			<string>constant.numeric.cfdg</string>
		</dict>
		<key>rule</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.rule.begin.cfdg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#loop</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#shape-replacement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>rule-directive</key>
		<dict>
			<key>begin</key>
			<string>\b(rule)\s++([a-zA-Z_][a-zA-Z_\.\d]*+)(\s++(((\d++)?(\.))?\d++))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.rule.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.definition.cfdg</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.cfdg</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.integer-float.cfdg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.rule.end.cfdg</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>shape-adjustment-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.unordered-block.begin.cfdg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#color-adjustment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#geometry-adjustment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.ordered-block.begin.cfdg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#color-adjustment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#geometry-adjustment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>shape-replacement</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z_][a-zA-Z_\.\d]*+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.cfdg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})|(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.unordered-block.end.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.ordered-block.end.cfdg</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#shape-adjustment-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>startshape-directive</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.startshape.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(startshape)\s++([a-zA-Z_][a-zA-Z_\.\d]*+)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cfdg</string>
	<key>uuid</key>
	<string>8D0EE5A2-FB60-40F8-8D0F-1E1FFB506462</string>
</dict>
</plist>
