<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gtd</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>GTD</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>[A-Z][a-z]+([A-Z][a-z]*)+</string>
			<key>name</key>
			<string>markup.other.pagename</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^-\s{2}\S+\s</string>
			<key>name</key>
			<string>string.unquoted.gtd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^&lt;-\s\S+\s</string>
			<key>name</key>
			<string>entity.name.tag.gtd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^-&gt;\s\S+\s</string>
			<key>name</key>
			<string>constant.language.gtd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\+\s{2}\S+\s</string>
			<key>name</key>
			<string>variable.language.gtd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\^\s{2}\S+\s</string>
			<key>name</key>
			<string>comment.line.gtd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\!\s{2}\S+\s</string>
			<key>name</key>
			<string>support.class.exception.gtd</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.markdown.wiki.gtd</string>
	<key>uuid</key>
	<string>A984336E-2C65-4152-8FC0-34D2E73721DA</string>
</dict>
</plist>
