<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>b</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Limbo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.limbo</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.limbo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(con|continue|cyclic|fn|hd|implement|import|include|len|load|module|of|or|pick|self|spawn|string|tagof|tl|to|type)\b</string>
			<key>name</key>
			<string>keyword.other.limbo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords that delimit flow blocks</string>
			<key>match</key>
			<string>\b(alt|break|case|else|do|for|if|return|while|with|)\b</string>
			<key>name</key>
			<string>keyword.control.flow.limbo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(byte|int|big|real|string|array|list|chan|adt|ref)\b</string>
			<key>name</key>
			<string>storage.type.limbo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(nil|\\0)\b</string>
			<key>name</key>
			<string>constant.language.limbo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>bitwise</string>
			<key>match</key>
			<string>\b(\&amp;|\^|&lt;&lt;|&gt;&gt;|\|)\b</string>
			<key>name</key>
			<string>keyword.operator.bitwise.limbo</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>logical</string>
			<key>match</key>
			<string>\b(\&amp;\&amp;|\|\|)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.limbo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;|&gt;|&lt;\=|&gt;\=|\=\=|\!\=</string>
			<key>name</key>
			<string>keyword.operator.comparison.limbo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.limbo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\:\=|\=</string>
			<key>name</key>
			<string>keyword.operator.assignment.limbo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.limbo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.limbo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.limbo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\([abtnvfr0\\'"]|\\u(([0-7]|([A..F]|[a..f])){4}))</string>
					<key>name</key>
					<string>constant.character.escape.limbo</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.limbo</string>
	<key>uuid</key>
	<string>9B92490C-5D4C-419A-91AC-58F677BAB929</string>
</dict>
</plist>
