<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>slax</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{</string>
	<key>foldingStopMarker</key>
	<string>\}</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>SLAX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.slax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.slax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\/[-a-zA-Z0-9_]+|[-a-zA-Z0-9_]+\/[-a-zA-Z0-9_]+|\/[-a-zA-Z0-9_]+\/[-a-zA-Z0-9_]+)</string>
			<key>name</key>
			<string>constant.namespace.slax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(apply-templates|call|else|for-each|if|match|mode|param|priority|template|var|version|with)\b</string>
			<key>name</key>
			<string>keyword.control.slax</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.sub.slax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.slax</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.method.slax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(call)\s+([-a-zA-Z0-9_:]+)\s*(\([\$\@\*;]*\))?</string>
			<key>name</key>
			<string>meta.call.slax</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.slax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.method.slax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([-a-zA-Z0-9_]+)\s*(\([\$;]*\))?</string>
			<key>name</key>
			<string>meta.method.slax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;)([a-zA-Z0-9:]+)</string>
			<key>end</key>
			<string>(&gt;)</string>
			<key>name</key>
			<string>meta.tag.slax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.slax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.slax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.slax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.slax</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.slax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.slax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.slax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.slax</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(copy-of|expr|import|not|ns junos|ns xnm|ns jcs)\b</string>
			<key>name</key>
			<string>support.function.slax</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.slax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$)([-a-zA-Z0-9_\$])*\b</string>
			<key>name</key>
			<string>variable.other.readwrite.global.slax</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.slax</string>
	<key>uuid</key>
	<string>AAD4AAB9-384A-4DB4-A301-22E1D3747328</string>
</dict>
</plist>
