{
	name = "Makefile";
	fileTypes = ( GNUmakefile, makefile, Makefile );
	patterns = (
		{ name = "keywords.variables.makefile"; match = "^(\\w|[-_])+\\s*=.*"; fontStyle = ( bold ); foregroundColor = "red"; },
		{ name = "comments.line.makefile"; match = "^#.*"; fontStyle = ( italic ); foregroundColor = "gray"; },
		{ name = "keywords.directives.makefile"; match = "^(\\s*)\\<(\\-??include|ifeq|ifneq|ifdef|ifndef|else|endif|vpath|export|unexport|define|endef|override)\\>"; fontStyle = ( bold ); "foregroundColor[2]" = "#008800"; },
		{ name = "rule.makefile"; match = "^([^\\t ]+:(?!\\=))\\s*.*"; "fontStyle[1]" = ( bold ); foregroundColor = "blue"; }
	);
}
