<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>apt</string>
		<string>apt.vm</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>Almost Plain Text (APT)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s+-{3,}$\n</string>
			<key>end</key>
			<string>^\s+-{3,}$\n</string>
			<key>name</key>
			<string>meta.heading.apt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s+\w.+$\n?</string>
					<key>name</key>
					<string>markup.heading.title-author-or-date.apt</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\+---(?:-*)\+?\s*$</string>
			<key>contentName</key>
			<string>markup.raw.block.apt</string>
			<key>end</key>
			<string>^\+---(?:-*)\+?\s*$</string>
			<key>name</key>
			<string>meta.block-level.apt</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s{2,}(?=\w.*$)</string>
			<key>end</key>
			<string>^(?=\s*$)</string>
			<key>name</key>
			<string>meta.paragraph.apt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#headings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lists</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*~~.*$\n?</string>
					<key>name</key>
					<string>comment.line.tilde.apt</string>
				</dict>
			</array>
		</dict>
		<key>formatting</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.begin.apt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.content.raw.apt</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.end.apt</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;&lt;&lt;)(.*?)(&gt;&gt;&gt;)</string>
					<key>name</key>
					<string>markup.raw.inline.apt</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;&lt;</string>
					<key>end</key>
					<string>&gt;&gt;</string>
					<key>name</key>
					<string>markup.bold.inline.apt</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;.*?&gt;</string>
					<key>name</key>
					<string>markup.italic.inline.apt</string>
				</dict>
			</array>
		</dict>
		<key>headings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\w.*$\n?</string>
					<key>name</key>
					<string>markup.heading.2.apt</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\*\s+.*$\n?</string>
					<key>name</key>
					<string>markup.heading.3.apt</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\*\*\s+.*$\n?</string>
					<key>name</key>
					<string>markup.heading.4.apt</string>
				</dict>
			</array>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#formatting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#links</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#velocity-token</string>
				</dict>
			</array>
		</dict>
		<key>links</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>({{)({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.begin.apt</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.address.begin.apt</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.end.apt</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.link.inline.apt</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;={)</string>
							<key>contentName</key>
							<string>markup.underline.link.apt</string>
							<key>end</key>
							<string>}</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.link.address.end.apt</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#velocity-token</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=})</string>
							<key>contentName</key>
							<string>string.other.link.title.apt</string>
							<key>end</key>
							<string>(?=})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#velocity-token</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>lists</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s+\*</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>markup.list.unnumbered.apt</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>velocity-token</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\$\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.apt</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>variable.other.velocity-token.apt</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.apt</string>
	<key>uuid</key>
	<string>B43D89E6-85EF-414C-B0F3-EB99A90D1BE6</string>
</dict>
</plist>
