<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>crontab</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Crontab</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*#.+$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.crontab</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.minute.crontab</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>keyword.other.crontab</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.input.crontab</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>keyword.other.input-separator.crontab</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.hour.crontab</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.day-of-month.crontab</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.month.crontab</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.other.month.crontab</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.day-of-week.crontab</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.other.weekday.crontab</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.other.special.schedule.crontab</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.command.crontab</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>This doesn't work as it should do for multiple %s</string>
			<key>match</key>
			<string>(?x)^\s*
			        (?:
    			        ((?:\*|(?:\d+|\*)(?:[-,\/]\d+)*))\s+        # Minute
						((?:\*|(?:\d+|\*)(?:[-,\/]\d+)*))\s+        # Hour
						((?:\*|(?:\d+|\*)(?:[-,\/]\d+)*))\s+        # Day of the month
						((?:\*|(?:\d+|\*)(?:[-,\/]\d+)*|((?i:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec))))\s+   # Month
						((?:\*|[0-7*](?:[-,\/][0-7])*|((?i:Mon|Tue|Wed|Thu|Fri|Sat|Sun))))\s+                       # Day of the week
						|
						(\@(?:reboot|midnight|(?:year|annual|month|week|dai|hour)ly)\b)   # Special keywords
					)
					(
						(?:(@AppleNotOnBattery)\s+)?
						.+?   # The command
					)
					((?&lt;!\\)(%).*?)*	# Optional standard input for the command
					\s*$\n?</string>
			<key>name</key>
			<string>meta.schedule.crontab</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.environment.crontab</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.begin.crontab</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.language.mailto.crontab</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.end.crontab</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign.crontab</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other.value.crontab</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.crontab</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.crontab</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)^\s*
					(
						(['"]|)
						(?i:(MAILTO)|.+?)
						(\2)
					)
					\s*(=)\s*
					(
						(['"]|)
						.+?
						(\7)
					)
					\s*$\n?</string>
			<key>name</key>
			<string>meta.environment-assign.crontab</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.crontab</string>
	<key>uuid</key>
	<string>B646698B-E6E0-4257-9352-C844D3FB5FFB</string>
</dict>
</plist>
