<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vm</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		\#(?:
			    (?:macro|if|foreach)\b \s* \(
			|\{ (?:macro|if|foreach)\b \s* \(
		).*(?!\#\{?end).*$</string>
	<key>foldingStopMarker</key>
	<string>\#end\b|\#\{end</string>
	<key>keyEquivalent</key>
	<string>^@V</string>
	<key>name</key>
	<string>Velocity</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backslash.velocity</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\\[\!\#\$\\]</string>
			<key>name</key>
			<string>source.velocity.embedded</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directives</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-number-sign</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.velocity</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\#\#).*$\n?</string>
			<key>name</key>
			<string>source.velocity.embedded</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=#\*)</string>
			<key>end</key>
			<string>(?&lt;=\*#|\*#\n)</string>
			<key>name</key>
			<string>source.velocity.embedded</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\#\*\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.velocity</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*\#\n?</string>
					<key>name</key>
					<string>comment.block.documentation</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\#\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.velocity</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*\#\n?</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.range.begin.java</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.java</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.continuation.range.java</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.java</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.range.end.java</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)(-?\d+)(\.\.)(-?\d+)(\])</string>
					<key>name</key>
					<string>meta.definition.range.java</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.begin.velocity</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.end.velocity</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.structure.array.velocity</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest-brackets</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#array</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.array.velocity</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.velocity</string>
				</dict>
			</array>
		</dict>
		<key>directives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.velocity</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.begin.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.end.velocity</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
						(\#) (?: 
							      \b(?:else|end)\b 
							|(\{) \b(?:else|end)\b (\})
						)</string>
					<key>name</key>
					<string>source.velocity.embedded</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>((#)\b(?:macro)\b)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.macro.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.velocity</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.velocity</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.velocity.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.module.macro.velocity</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?&lt;=#macro\()\s*([_a-zA-Z][-a-zA-Z0-9_]*)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#directives-arguments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((#)\b(?:set)\b)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.variable.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.velocity</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.velocity</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.velocity.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#directives-arguments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((#)\b(?:if|elseif|foreach)\b)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.velocity</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.velocity</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.velocity.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#directives-arguments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((#)\b(?:[a-zA-Z][-a-zA-Z0-9_]*)\b)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.velocity</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.velocity</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.velocity.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#directives-arguments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((#)\b(?:[a-zA-Z][-a-zA-Z0-9_]*)\b)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.velocity</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.velocity</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.velocity.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#directives-arguments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>directives-arguments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nest-parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directives</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?x)
						 ((\$ \!?   ) [a-zA-Z][-a-zA-Z0-9_]* \b) 
							( (?:(\.) [a-zA-Z][-a-zA-Z0-9_]* \b)* ) 
							( (?:(\.) [a-zA-Z][-a-zA-Z0-9_]* \b)+ ) (\()\s* 
					</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.method.with-arguments.velocity</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.velocity</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.parameters.velocity</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.velocity</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.velocity</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.velocity</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.velocity</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.velocity.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#function-arguments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)
						 ((\$ \!? \{) [a-zA-Z][-a-zA-Z0-9_]* \b) 
							( (?:(\.) [a-zA-Z][-a-zA-Z0-9_]* \b)* ) 
							( (?:(\.) [a-zA-Z][-a-zA-Z0-9_]* \b)+ ) (\()\s* 
					</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.method.with-arguments.velocity</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.velocity</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.parameters.velocity</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.velocity</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.velocity</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.velocity</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*(\))(\s*(\}))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.velocity</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.velocity.embedded</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#function-arguments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function-arguments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.method.with-arguments.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.velocity</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.velocity</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.velocity</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
					\s* (\))( ( (?:(\.) [a-zA-Z][-a-zA-Z0-9_]* \b)+ ) (\()\s* )
					</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nest-parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directives</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|while|for|in|foreach|return|ifelse|else|case|macro|end|stop)\b</string>
					<key>name</key>
					<string>keyword.control.velocity</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(set|parse|cparse|config|include|cinclude)\b</string>
					<key>name</key>
					<string>keyword.velocity</string>
				</dict>
			</array>
		</dict>
		<key>nest-brackets</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest-parens</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>nest-curly</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest-parens</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>nest-parens</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest-parens</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bin\b</string>
					<key>name</key>
					<string>keyword.operator.assignment.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;)</string>
					<key>name</key>
					<string>keyword.operator.comparison.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.operator.assignment.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-\-|\+\+)</string>
					<key>name</key>
					<string>keyword.operator.increment-decrement.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-|\+|\*|\/|%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(!|&amp;&amp;|\|\|)</string>
					<key>name</key>
					<string>keyword.operator.logical.java</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.velocity</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.velocity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#directives</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\$\{</string>
							<key>end</key>
							<string>\}</string>
							<key>name</key>
							<string>source.velocity.embedded.source</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.velocity</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\'</string>
							<key>name</key>
							<string>constant.character.escape.velocity</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.velocity</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.velocity</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.parameters.velocity</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.velocity</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.velocity</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.velocity</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.parameters.velocity</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.velocity</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
						 ((\$ \!?   ) [a-zA-Z][-a-zA-Z0-9_]*) \b ( (?: (\.) [a-zA-Z][-a-zA-Z0-9_]* \b)+ ) (?!\()
						|((\$ \!? \{) [a-zA-Z][-a-zA-Z0-9_]*) \b ( (?: (\.) [a-zA-Z][-a-zA-Z0-9_]* \b)+ ) ((\}))
					</string>
					<key>name</key>
					<string>source.velocity.embedded</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.other.readwrite.velocity</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.velocity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.velocity</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.velocity</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
						 (\$ \!?   ) [a-zA-Z][-a-zA-Z0-9_]* \b
						|(\$ \!? \{) [a-zA-Z][-a-zA-Z0-9_]* \b (\})
					</string>
					<key>name</key>
					<string>source.velocity.embedded</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.velocity</string>
	<key>uuid</key>
	<string>460426C7-D079-49DB-8E50-8E0B938644CA</string>
</dict>
</plist>
