<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>y</string>
	</array>
	<key>name</key>
	<string>Bison</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^%\{</string>
			<key>contentName</key>
			<string>source.c</string>
			<key>end</key>
			<string>%\}</string>
			<key>name</key>
			<string>meta.prologue.bison</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?!%%$)</string>
			<key>end</key>
			<string>^(?=%%$)</string>
			<key>name</key>
			<string>meta.declarations.bison</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^%%$</string>
			<key>end</key>
			<string>$.^</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(?!%%$)</string>
					<key>contentName</key>
					<string>meta.rules.bison</string>
					<key>end</key>
					<string>^(?=%%$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^%%$</string>
					<key>contentName</key>
					<string>meta.epilogue.bison</string>
					<key>end</key>
					<string>$.^</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^</string>
							<key>end</key>
							<string>$.^</string>
							<key>name</key>
							<string>source.c</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.c</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.bison</string>
	<key>uuid</key>
	<string>1AA6D027-D1AF-4868-951D-1634BD88D910</string>
</dict>
</plist>
