<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pom.xml</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>Maven POM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#profiles</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pom-body</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#maven-xml</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>build</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(build)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.build.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(build)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.build.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.build.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#plugins</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#extensions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>dependencies</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(dependencies)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.dependencies.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(dependencies)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.dependencies.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.dependencies.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#dependency</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>dependency</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(dependency)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.dependency.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(dependency)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.dependency.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.dependency.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=&lt;artifactId&gt;)</string>
							<key>end</key>
							<string>(?=&lt;/artifactId&gt;)</string>
							<key>name</key>
							<string>meta.dependency-id.xml.pom</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>distributionManagement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(distributionManagement)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.distributionManagement.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(distributionManagement)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.distributionManagement.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.distributionManagement.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>extension</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(extension)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.extension.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(extension)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.extension.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.extension.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=&lt;artifactId&gt;)</string>
							<key>end</key>
							<string>(?=&lt;/artifactId&gt;)</string>
							<key>name</key>
							<string>meta.extension-id.xml.pom</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>extensions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(extensions)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.extensions.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(extensions)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.extensions.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.extensions.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#extension</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>groovy-plugin</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>((&lt;)(artifactId)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;))(groovy-maven-plugin)((&lt;/)(artifactId)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.groovy-plugin.identifier.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.artifactId.begin.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>meta.plugin-id.xml.pom</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>meta.tag.artifactId.begin.xml.pom</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=&lt;/plugin&gt;)</string>
					<key>name</key>
					<string>meta.plugin.groovy-plugin.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(&lt;)(source)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.tag.plugin.begin.xml.pom</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml.pom</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.xml.pom</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml.pom</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.groovy</string>
							<key>end</key>
							<string>(&lt;/)(source)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.tag.plugin.end.xml.pom</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml.pom</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.xml.pom</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml.pom</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.source.groovy.xml.pom</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.groovy</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>maven-xml</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\${</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>variable.other.expression.xml.pom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<key>plugin</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(plugin)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.plugin.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(plugin)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.plugin.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.plugin.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#groovy-plugin</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=&lt;artifactId&gt;)</string>
							<key>end</key>
							<string>(?=&lt;/artifactId&gt;)</string>
							<key>name</key>
							<string>meta.plugin-id.xml.pom</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>plugins</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(plugins)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.plugins.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(plugins)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.plugins.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.plugins.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#plugin</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>pom-body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dependencies</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#repositories</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#build</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reporting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#distributionManagement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#maven-xml</string>
				</dict>
			</array>
		</dict>
		<key>profile</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(profile)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.profile.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(profile)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.profile.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.profile.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=&lt;id&gt;)</string>
							<key>end</key>
							<string>(?=&lt;/id&gt;)</string>
							<key>name</key>
							<string>meta.profile-id.xml.pom</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pom-body</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>profiles</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(profiles)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.profiles.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(profiles)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.profiles.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.profiles.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#profile</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>properties</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(properties)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.properties.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(properties)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.properties.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.properties.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(&lt;)(\w+)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.tag.property.begin.xml.pom</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml.pom</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.xml.pom</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml.pom</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(&lt;/)(\w+)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.tag.property.end.xml.pom</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml.pom</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.xml.pom</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml.pom</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.property.xml.pom</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>reporting</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(reporting)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.reporting.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(reporting)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.reporting.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.reporting.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#plugins</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>repositories</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(repositories)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.repositories.begin.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)(repositories)\s*(&gt;)(?!&lt;\s*/\2\s*&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.repositories.end.xml.pom</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.pom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml.pom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.repositories.xml.pom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#maven-xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.xml.pom</string>
	<key>uuid</key>
	<string>FF85557D-4A93-4CD0-954C-DB74F36A27D8</string>
</dict>
</plist>
