<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>foldingStartMarker</key>
	<string></string>
	<key>foldingStopMarker</key>
	<string></string>
	<key>keyEquivalent</key>
	<string>^~U</string>
	<key>name</key>
	<string>Unicode Highlight Combining Marks</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>[\x{0300}-\x{036F}\x{1DC0}-\x{1DFF}\x{20D0}-\x{20FF}\x{FE20}-\x{FE2F}]+</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>unicode.check.combiningMarks</string>
	<key>uuid</key>
	<string>B48EDCF6-3E73-4115-A0C9-10B17778F8F5</string>
</dict>
</plist>
