<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Yahoo User Interface Library</string>
	<key>foldingStartMarker</key>
	<string>(^.*{[^}]*$|^.*\([^\)]*$|^.*/\*(?!.*\*/).*$)</string>
	<key>foldingStopMarker</key>
	<string>(^\s*\}|^\s*\)|^(?!.*/\*).*\*/)</string>
	<key>name</key>
	<string>Javascript YUI</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(YAHOO)\b</string>
			<key>name</key>
			<string>support.class.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(util|widget|example)\b</string>
			<key>name</key>
			<string>support.class.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(CustomEvent|Subscriber|Event|Dom|Point|Region|Connect|DD|DDProxy|DDTarget|DragDrop|DragDropMgr|DDM|Anim|AnimMgr|Bezier|ColorAnim|Easing|Motion)\b</string>
			<key>name</key>
			<string>support.class.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(extend|log|namespace)\b(?=\()</string>
			<key>name</key>
			<string>support.function.YAHOO.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.()\b(?=\()</string>
			<key>name</key>
			<string>support.function.Subscriber.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(fire|subscribe|unsubscribe|unsubscribeAll)\b(?=\()</string>
			<key>name</key>
			<string>support.function.CustomEvent.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(on|addListener|generateId|getCharCode|getEvent|getListeners|getPageX|getPageY|getRelatedTarget|getTarget|getTime|getXY|onAvailable|preventDefault|purgeElement|removeListener|resolveTextNode|stopEvent|stopPropagation)\b(?=\()</string>
			<key>name</key>
			<string>support.function.Event.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(addClass|batch|generateId|get|getViewportHeight|getViewportWidth|getElementsBy|getElementsByClassName|getRegion|getStyle|getX|getXY|getY|hasClass|inDocument|isAncestor|removeClass|replaceClass|setStyle|setX|setXY|setY)\b(?=\()</string>
			<key>name</key>
			<string>support.function.Dom.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(contains|getArea|intersect|union|getRegion)\b(?=\()</string>
			<key>name</key>
			<string>support.function.Region.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(abort|asyncRequest|createExceptionObject|createResponseObject|createXhrObject|getConnectionObject|handleReadyState|handleTransactionResponse|initHeader|isCallInProgress|releaseObject|setDefaultPostHeader|setForm|setHeader|setPollingInterval|setProgId)\b(?=\()</string>
			<key>name</key>
			<string>support.function.Connect.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(alignElWithMouse|applyConfig|autoOffset|b4Drag|b4MouseDown|cachePosition|setDelta|setDragElPos)\b(?=\()</string>
			<key>name</key>
			<string>support.function.DD.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(applyConfig|b4EndDrag|b4MouseDown|b4StartDrag|createFrame|endDrag|initFrame)\b(?=\()</string>
			<key>name</key>
			<string>support.function.DDProxy.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(addInvalidHandleClass|addInvalidHandleId|addInvalidHandleType|addToGroup|applyConfig|clearConstraints|clearTicks|endDrag|getDragEl|getEl|initTarget|isLocked|isValidHandleChild|lock|onAvailable|onDrag|onDragDrop|onDragEnter|onDragOut|onDragOver|onMouseDown|onMouseUp|removeFromGroup|removeInvalidHandleClass|removeInvalidHandleId|removeInvalidHandleType|resetContraints|setDragElId|setHandleElId|setInitPosition|setOuterHandleElId|setPadding|setXConstraint|setYConstraint|startDrag|unlock|unreg)\b(?=\()</string>
			<key>name</key>
			<string>support.function.DragDrop.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(getBestMatch|getClientHeight|getClientWidth|getCss|getDDById|getElement|getLocation|getPosX|getPosY|getRelated|getScrollLeft|getScrollTop|getStyle|handleWasClicked|isDragDrop|isHandle|isLegalTarget|isLocked|isTypeOfDD|lock|moveToEl|numericSort|refreshCache|regDragDrop|regHandle|startDrag|stopEvent|swapNode|unlock|verifyEl)\b(?=\()</string>
			<key>name</key>
			<string>support.function.DragDropMgr.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(animate|doMethod|getAttribute|getDefaultUnit|getEl|getStartTime|isAnimated|setAttribute|stop)\b(?=\()</string>
			<key>name</key>
			<string>support.function.Anim.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(registerElement|run|start|stop|unregister)\b(?=\()</string>
			<key>name</key>
			<string>support.function.AnimMgr.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(getPosition)\b(?=\()</string>
			<key>name</key>
			<string>support.function.Bezier.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(parseColor)\b(?=\()</string>
			<key>name</key>
			<string>support.function.ColorAnim.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(backBoth|backIn|backOut|bounceBoth|bounceIn|bounceOut|easeBoth|easeBothStrong|easeIn|easeInStrong|easeNone|easeOut|easeOutStrong|elasticBoth|elasticIn|elasticOut)\b</string>
			<key>name</key>
			<string>support.function.Easing.js.yui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(doMethod|getAttribute|setAttribute)\b(?=\()</string>
			<key>name</key>
			<string>support.function.Motion.js.yui</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js.yui</string>
	<key>uuid</key>
	<string>62E7EF93-5574-4063-BF18-AD38620236B9</string>
</dict>
</plist>
