<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pom.xml</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>Maven POM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>((&lt;)(dependencies)(&gt;))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.dependencies.begin.pom.xml</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>((&lt;/)(dependencies)(&gt;))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.dependencies.end.pom.xml</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.dependencies.pom.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>((&lt;)(dependency)(&gt;))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.dependencies.dependency.begin.pom.xml</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>((&lt;/)(dependency)(&gt;))</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.dependencies.dependency.end.pom.xml</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.dependencies.dependency.pom.xml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=&lt;repositories&gt;)</string>
			<key>end</key>
			<string>(?&lt;=&lt;/repositories&gt;)</string>
			<key>name</key>
			<string>meta.repositories.pom.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>((&lt;)(build)(&gt;))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.build.begin.pom.xml</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>((&lt;/)(build)(&gt;))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.build.end.pom.xml</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.build.pom.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>((&lt;)(plugins)(&gt;))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.build.plugins.begin.pom.xml</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>((&lt;/)(plugins)(&gt;))</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.build.plugins.end.pom.xml</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.xml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.build.plugins.pom.xml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>((&lt;)(plugin)(&gt;))</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.build.plugins.plugin.begin.pom.xml</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.tag.xml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.xml</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>((&lt;/)(plugin)(&gt;))</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.build.plugins.plugin.end.pom.xml</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.tag.xml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.xml</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.xml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.build.plugins.plugin.pom.xml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(?&lt;=&lt;artifactId&gt;)</string>
									<key>end</key>
									<string>(?=&lt;/artifactId&gt;)</string>
									<key>name</key>
									<string>meta.build.plugins.plugin.id.pom.xml</string>
								</dict>
								<dict>
									<key>include</key>
									<string>text.xml</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.pom.xml</string>
	<key>uuid</key>
	<string>FF85557D-4A93-4CD0-954C-DB74F36A27D8</string>
</dict>
</plist>
