<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>Rnw</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^@\s|^&lt;&lt;.*(?&lt;!@)&gt;&gt;=</string>
	<key>foldingStopMarker</key>
	<string>^@\s|^&lt;&lt;.*(?&lt;!@)&gt;&gt;=</string>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>Rweave</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#rweave-escapes</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(@)(?: (.*)|\n)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.rweave</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>text.tex.latex.embedded.rweave</string>
			<key>end</key>
			<string>^(?=@\s|&lt;&lt;.*(?&lt;!@)&gt;&gt;=)</string>
			<key>name</key>
			<string>meta.scope.documentation.embedded.rweave</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>text.tex.latex.embedded.rweave</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-reference</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rweave-escapes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.tex.latex</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(&lt;&lt;(.*)(?&lt;!@)&gt;&gt;)=(.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.block-tag.rweave</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.rweave</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.rweave</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.r.embedded.rweave</string>
			<key>end</key>
			<string>^(?=@\s|&lt;&lt;.*(?&lt;!@)&gt;&gt;=)</string>
			<key>name</key>
			<string>meta.scope.source.rweave</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rweave-escapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.r</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>In the absence of an opening chunk, documentation is assumed</string>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-reference</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.rweave</string>
				</dict>
			</dict>
			<key>match</key>
			<string>&lt;&lt;(.*)(?&lt;!@)&gt;&gt;</string>
		</dict>
		<key>rweave-escapes</key>
		<dict>
			<key>match</key>
			<string>@(@|&lt;&lt;|&gt;&gt;|\[\[|\]\])</string>
			<key>name</key>
			<string>constant.character.escape.rweave</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.rweave</string>
	<key>uuid</key>
	<string>EA4FEB89-887C-4F0B-879A-3808958105FB</string>
</dict>
</plist>
