<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>wikidot</string>
	</array>
	<key>firstLineMatch</key>
	<string>^\s*={2,}(.*)={2,}\s*$</string>
	<key>foldingStartMarker</key>
	<string>(&lt;(php|html|file|nowiki)&gt;|&lt;code(\s*.*)?&gt;)|/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>(&lt;/(code|php|html|file|nowiki)&gt;)|\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~W</string>
	<key>name</key>
	<string>Wikidot</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#php</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.wikidot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.wikidot</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.wikidot</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.wikidot</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string> derived from html comment, replacing angle brackets with square</string>
			<key>match</key>
			<string>\[!--.*--\]</string>
			<key>name</key>
			<string>punctuation.definition.comment.wikidot</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[!--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.wikidot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--\s*\]</string>
			<key>name</key>
			<string>comment.block.wikidot</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[!--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.wikidot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--\]</string>
			<key>name</key>
			<string>comment.block.documentation.wikidot</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.wikidot</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\+{1,})(.*)$\n?</string>
			<key>name</key>
			<string>markup.heading.wikidot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*-{4,}\s*$\n?</string>
			<key>name</key>
			<string>meta.separator.wikidot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\\\\s</string>
			<key>name</key>
			<string>markup.other.paragraph.wikidot</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([\t ]?)(\*)</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.wikidot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>markup.list.unnumbered.wikidot</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([\t ]+)?(\#)</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.wikidot</string>
				</dict>
			</dict>
			<key>comment</key>
			<string># list item</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>markup.list.numbered.wikidot</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[|^]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.table.wikidot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.other.table.wikidot</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\&lt;)(file|nowiki)(\&gt;)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.template.wikidot</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.wikidot</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.wikidot</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.wikidot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;\/)(\2)(\&gt;)</string>
			<key>name</key>
			<string>markup.raw.wikidot</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(%%|\'\')</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.wikidot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\1</string>
			<key>name</key>
			<string>markup.raw.wikidot</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;)(html)(&gt;)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.template.block.wikidot</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.wikidot</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.wikidot</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.wikidot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)(html)(&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^((\s\s)|(\t))[^\*\-#].*$\n?</string>
			<key>name</key>
			<string>markup.raw.wikidot</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\&lt;)(sub|sup|del)(\&gt;)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.template.wikidot</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.wikidot</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.wikidot</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.wikidot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\&lt;/)(\2)(\&gt;)</string>
			<key>name</key>
			<string>markup.other.wikidot</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;)(code)(?:\s+[^&gt;]*)?(&gt;)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.template.code.wikidot</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.wikidot</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.wikidot</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.wikidot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)(code)(&gt;)</string>
			<key>name</key>
			<string>markup.raw.wikidot</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\*\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.wikidot</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*\*</string>
					<key>name</key>
					<string>markup.bold.wikidot</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.wikidot</string>
						</dict>
					</dict>
					<key>end</key>
					<string>//</string>
					<key>name</key>
					<string>markup.italic.wikidot</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>__</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.underline.wikidot</string>
						</dict>
					</dict>
					<key>end</key>
					<string>__</string>
					<key>name</key>
					<string>markup.underline.wikidot</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.image.wikidot</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.wikidot</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.image.wikidot</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{\{)(.+?)(\}\})</string>
					<key>name</key>
					<string>meta.image.inline.wikidot</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.wikidot</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.wikidot</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>[#anchorName display text]</string>
					<key>match</key>
					<string>(\[)(#.+?) (.+?)(\])</string>
					<key>name</key>
					<string>meta.link.to.anchor.wikidot</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.wikidot</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.wikidot</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>[((bibcite Ebstein1996))]</string>
					<key>match</key>
					<string>(\[\(\()(bibcite) (.+?)(\)\)\])</string>
					<key>name</key>
					<string>meta.link.bibcite.wikidot</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.wikidot</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.wikidot</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>[[# anchor-name]]</string>
					<key>match</key>
					<string>(\[\[)(# )(.+?)(\]\])</string>
					<key>name</key>
					<string>meta.anchor.wikidot</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.wikidot</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.wikidot</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>[[[match any link]]]</string>
					<key>match</key>
					<string>(\[{1,3})([^\] ]*)(| )?([^\]]*)?(\]{1,3})</string>
					<key>name</key>
					<string>meta.link.wikidot</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.interwiki.wikidot</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[\[)([^\[\]]+\&gt;[^|\]]+)(\]\])</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.wikidot</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((https?|telnet|gopher|wais|ftp|ed2k|irc)://[\w/\#~:.?+=&amp;%@!\-;,]+?(?=[.:?\-;,]*[^\w/\#~:.?+=&amp;%@!\-;,]))</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.wikidot</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.wikidot</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;)([\w0-9\-_.]+?@[\w\-]+\.[\w\-\.]+\.*[\w]+)(\&gt;)</string>
					<key>name</key>
					<string>meta.link.email.wikidot</string>
				</dict>
			</array>
		</dict>
		<key>php</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.php</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s*)?(?=&lt;php&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.leading.wikidot</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.php</string>
					<key>end</key>
					<string>(?&lt;=&lt;/php&gt;)(?!&lt;php&gt;)(\s*$\n?)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.trailing.wikidot</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>((&lt;)(php)(&gt;))</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.embedded.begin.wikidot</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.tag.template.wikidot</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.wikidot</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.wikidot</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.wikidot</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.php</string>
							<key>end</key>
							<string>(((&lt;/))(php)(&gt;))</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.embedded.end.wikidot</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.tag.template.wikidot</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.wikidot</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>source.php</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.wikidot</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.wikidot</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.php</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.wikidot</string>
	<key>uuid</key>
	<string>3E4B200F-1C2B-46B9-A715-822F6C0CB4F5</string>
</dict>
</plist>
