<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>TODO: Folding?</string>
	<key>fileTypes</key>
	<array>
		<string>todo</string>
		<string>tasks</string>
		<string>todolist</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>Tasks</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#link</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(✓)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.list_item.leading.tasks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.tasks</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.paragraph.list.tasks</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>markup.list.completed.tasks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(-)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.list_item.leading.tasks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.tasks</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.paragraph.list.tasks</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>markup.list.pending.tasks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.list_item.leading.tasks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.header.tasks</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.toc-list.tasks</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.header.tasks</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*)((.+)(:)\s*$\n?)</string>
			<key>name</key>
			<string>meta.header-line.tasks</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>link</key>
		<dict>
			<key>match</key>
			<string>(https?|ftp|mailto):\S+?(?=[)&gt;,.':;"]*(\s|$)|$)</string>
			<key>name</key>
			<string>markup.underline.link.tasks</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.tasks</string>
	<key>uuid</key>
	<string>CDF5D65E-F8C5-4FD5-8BC3-D4BE8FE2C1EA</string>
</dict>
</plist>
