<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>
MooTools Framework by Valerio Proietti. 
http://mootools.net
This syntax document is largely based on the documentation at http://docs.mootools.net
Initial bundle by Joe Maller. 
</string>
	<key>foldingStartMarker</key>
	<string>(^.*{[^}]*$|^.*\([^\)]*$|^.*/\*(?!.*\*/).*$)</string>
	<key>foldingStopMarker</key>
	<string>(^\s*\}|^\s*\)|^(?!.*/\*).*\*/)</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>MooTools</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>
Class
The base class object of the http://mootools.net framework. 
http://docs.mootools.net/files/Core/Moo-js.html</string>
			<key>match</key>
			<string>\b(Class|Array|Element|Event|Function|String)\b</string>
			<key>name</key>
			<string>support.class.js.mootools</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(empty|extend|implement)\b</string>
			<key>name</key>
			<string>support.class.class.js.mootools</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(extend|Native)\b</string>
			<key>name</key>
			<string>support.function.class.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Utility
Contains Utility functions
http://docs.mootools.net/files/Core/Utility-js.html
</string>
			<key>match</key>
			<string>\$(type|chk|pick|random|clear)\b</string>
			<key>name</key>
			<string>support.function.utility.js.mootools</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.window.browser.js.mootools</string>
				</dict>
			</dict>
			<key>match</key>
			<string>window\.(ie|ie6|ie7|khtml|gecko)\b</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Array
A collection of The Array Object prototype methods.
http://docs.mootools.net/files/Native/Array-js.html</string>
			<key>include</key>
			<string>#array-functions</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(forEach|filter|map|every|some|indexOf|each|copy|remove|test|extend|associate)\b</string>
			<key>name</key>
			<string>support.class.array.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Element
Custom class to allow all of its methods to be used with any DOM element via the dollar function $.
http://docs.mootools.net/files/Native/Element-js.html</string>
			<key>include</key>
			<string>#element-functions</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(injectBefore|injectAfter|injectInside|adopt|remove|clone|replaceWith|appendText|hasClass|addClass|removeClass|toggleClass|setStyle|setStyles|setOpacity|getStyle|addEvent|removeEvent|removeEvents|fireEvent|getPrevious|getNext|getFirst|getLast|getParent|getChildren|setProperty|setProperties|setHTML|getProperty|getTag|scrollTo|getValue|getSize|getPosition|getTop|getLeft|getCoordinates)\b</string>
			<key>name</key>
			<string>support.class.element.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Event
Cross browser methods to manage events.
http://docs.mootools.net/files/Native/Event-js.html</string>
			<key>match</key>
			<string>\b(stop|stopPropagation|preventDefault|bindWithEvent)\b</string>
			<key>name</key>
			<string>support.class.event.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Function
A collection of The Function Object prototype methods.
http://docs.mootools.net/files/Native/Function-js.html</string>
			<key>match</key>
			<string>\b(create|pass|attempt|bind|bindAsEventListener|delay|periodical)\b</string>
			<key>name</key>
			<string>support.class.function.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
String
A collection of The String Object prototype methods.
http://docs.mootools.net/files/Native/String-js.html</string>
			<key>match</key>
			<string>\b(test|toInt|camelCase|hyphenate|capitalize|trim|clean|rgbToHex|hexToRgb)\b</string>
			<key>name</key>
			<string>support.class.string.js.mootools</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btoInt\b</string>
			<key>name</key>
			<string>support.class.number.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
DOM
Css Query related function and Element extensions.
http://docs.mootools.net/files/Addons/Dom-js.html</string>
			<key>include</key>
			<string>#dom-functions</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>document. getElementsByClassName	might belong somewhere else</string>
			<key>match</key>
			<string>\b(getElements|getElementById|getElement|getElementsBySelector|getElementsByClassName)\b</string>
			<key>name</key>
			<string>support.class.dom.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Hash
It wraps an object that it uses internally as a map.
http://docs.mootools.net/files/Addons/Hash-js.html
 -- note: several overlaps in here with named properties from array.js.mootools</string>
			<key>include</key>
			<string>#hash-functions</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(get|hasKey|set|remove|each|extend|empty|keys|values)\b</string>
			<key>name</key>
			<string>support.class.hash.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Color
Creates a new Color Object, which is an array with some color specific methods.
http://docs.mootools.net/files/Addons/Color-js.html</string>
			<key>match</key>
			<string>\b(mix|invert|setHue|setSaturation|setBrightness)\b</string>
			<key>name</key>
			<string>support.class.color.js.mootools</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.js</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\$(?:RGB|HSB)\(([^)]*)\)\b</string>
			<key>name</key>
			<string>support.function.color.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Common
Contains common implementations for custom classes.
http://docs.mootools.net/files/Addons/Common-js.html</string>
			<key>match</key>
			<string>\b(chain|(call|clear)Chain)\b</string>
			<key>name</key>
			<string>support.function.chain.js.mootools</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(add|fire|remove)Event\b</string>
			<key>name</key>
			<string>support.function.events.js.mootools</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bsetOptions\b</string>
			<key>name</key>
			<string>support.function.options.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Window Base
Cross browser methods to get the window size, onDomReady method.
http://docs.mootools.net/files/Window/Window-Base-js.html
 -- note: addEvent is already listed under Element</string>
			<key>match</key>
			<string>\bonDomReady\b</string>
			<key>name</key>
			<string>support.class.base.window.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Window Size
Cross browser methods to get various window dimensions.
http://docs.mootools.net/files/Window/Window-Size-js.html
 -- note: getSize is already listed under Element</string>
			<key>match</key>
			<string>\b(get(Width|Height|Scroll(Width|Height|Left|Top)))\b</string>
			<key>name</key>
			<string>support.class.size.window.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Ajax
An Ajax class, For all your asynchronous needs.
http://docs.mootools.net/files/Remote/Ajax-js.html</string>
			<key>match</key>
			<string>\b(request|evalScripts)\b</string>
			<key>name</key>
			<string>support.class.ajax.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>note: both Object and Element have a toQueryString function/property</string>
			<key>match</key>
			<string>\btoQueryString\b</string>
			<key>name</key>
			<string>support.function.js.mootools</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bsend\b</string>
			<key>name</key>
			<string>support.class.element.js</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Assets
provides dynamic loading for images, css and javascript files.
http://docs.mootools.net/files/Remote/Assets-js.html</string>
			<key>match</key>
			<string>\b(javascript|css|images?)\b</string>
			<key>name</key>
			<string>support.function.asset.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Cookie
Class for creating, getting, and removing cookies.
http://docs.mootools.net/files/Remote/Assets-js.html</string>
			<key>match</key>
			<string>\b(set|get|remove)\b</string>
			<key>name</key>
			<string>support.class.cookie.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Json
Simple Json parser and Stringyfier, See: http://www.json.org/
http://docs.mootools.net/files/Remote/Json-js.html</string>
			<key>match</key>
			<string>\b(toString|evaluate)\b</string>
			<key>name</key>
			<string>support.class.json.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Json Remote
Wrapped XHR with automated sending and receiving of Javascript Objects in Json Format.
http://docs.mootools.net/files/Remote/Json-Remote-js.html</string>
			<key>match</key>
			<string>\bJson\.Remote\b</string>
			<key>name</key>
			<string>support.class.json.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
XHR
Contains the basic XMLHttpRequest Class Wrapper.
http://docs.mootools.net/files/Remote/XHR-js.html</string>
			<key>match</key>
			<string>\bXHR\b</string>
			<key>name</key>
			<string>support.class.xhr.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Fx.Base			
Base class for the Mootools Effects (Moo.Fx) library.			
http://docs.mootools.net/files/Effects/Fx-Base-js.html</string>
			<key>match</key>
			<string>\b(set|start|stop)\b</string>
			<key>name</key>
			<string>support.class.base.fx.js.mootools</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(linear|sineInOut)\b</string>
			<key>name</key>
			<string>support.class.transitions.fx.js.mootools</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(onStart|onComplete|transition|duration|unit|wait|fps)\b</string>
			<key>name</key>
			<string>support.class.keys.options.transitions.fx</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Fx.Elements
Fx.Elements allows you to apply any number of styles transitions to a selection of elements.
http://docs.mootools.net/files/Effects/Fx-Elements-js.html</string>
			<key>match</key>
			<string>\b(start)\b</string>
			<key>name</key>
			<string>support.class.elements.fx.js.mootools</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(new)\s+(Fx\.Elements)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.new.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.instance.js.mootools</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.js</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.fx.elements.js.mootools</string>
			<key>end</key>
			<string>(\)(;|$))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.js</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dom-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hash-functions</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.js</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>variable.parameter.fx.elements.options.js.mootools</string>
					<key>end</key>
					<string>(\})(?=\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.js</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(:)</string>
							<key>name</key>
							<string>punctuation.separator.key-value.js.mootools</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#fx-options</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Fx.Scroll
Scroll any element with an overflow, including the window element.
http://docs.mootools.net/files/Effects/Fx-Scroll-js.html</string>
			<key>match</key>
			<string>\b(scrollTo|to(Top|Bottom|Left|Right|Element))</string>
			<key>name</key>
			<string>support.class.scroll.fx.js.mootools</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(new)\s+(Fx\.Scroll)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.new.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.instance.js.mootools</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.js</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.fx.scroll.js.mootools</string>
			<key>end</key>
			<string>(\)(;|$))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.js</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dom-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hash-functions</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.js</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>variable.parameter.fx.scroll.options.js.mootools</string>
					<key>end</key>
					<string>(\})(?=\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.js</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(:)</string>
							<key>name</key>
							<string>punctuation.separator.key-value.js.mootools</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#fx-options</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Fx.Slide
The slide effect; slides an element in horizontally or vertically, the contents will fold inside.
http://docs.mootools.net/files/Effects/Fx-Slide-js.html</string>
			<key>match</key>
			<string>\b(slide(In|Out)|hide|show|toggle)\b</string>
			<key>name</key>
			<string>support.class.slide.fx.js.mootools</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(new)\s+(Fx\.Slide)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.new.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.instance.js.mootools</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.js</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.fx.slide.js.mootools</string>
			<key>end</key>
			<string>(\)(;|$))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.js</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dom-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hash-functions</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.js</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>variable.parameter.fx.slide.options.js.mootools</string>
					<key>end</key>
					<string>(\})(?=\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.js</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(:)</string>
							<key>name</key>
							<string>punctuation.separator.key-value.js.mootools</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#fx-options</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Fx.Style
The Style effect; Extends Fx.Base, inherits all its properties.
http://docs.mootools.net/files/Effects/Fx-Style-js.html</string>
			<key>match</key>
			<string>\b(hide|start)\b</string>
			<key>name</key>
			<string>support.class.slide.fx.js.mootools</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(new)\s+(Fx\.Style)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.new.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.instance.fx.style.js.mootools</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.js</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.fx.style.js.mootools</string>
			<key>end</key>
			<string>(\)(;|$))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.js</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dom-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hash-functions</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>,\s*(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.js</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>variable.parameter.fx.style.options.js.mootools</string>
					<key>end</key>
					<string>(\})(?=\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.js</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(:)</string>
							<key>name</key>
							<string>punctuation.separator.key-value.js.mootools</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#fx-options</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(effect)\b</string>
			<key>name</key>
			<string>support.class.element.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Fx.Styles
Allows you to animate multiple css properties at once; Extends Fx.Base, inherits all its properties. 
http://docs.mootools.net/files/Effects/Fx-Styles-js.html</string>
			<key>match</key>
			<string>\b(start)\b</string>
			<key>name</key>
			<string>support.class.styles.fx.js.mootools</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(new)\s+(Fx\.Styles)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.new.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.instance.js.mootools</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.js</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.fx.styles.js.mootools</string>
			<key>end</key>
			<string>(\)(;|$))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.js</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dom-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hash-functions</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.js</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>variable.parameter.fx.styles.options.js.mootools</string>
					<key>end</key>
					<string>(\})(?=\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.js</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(:)</string>
							<key>name</key>
							<string>punctuation.separator.key-value.js.mootools</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#fx-options</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(effects)\b</string>
			<key>name</key>
			<string>support.class.element.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Fx.Transitions
A collection of tweaning transitions for use with the Fx.Base classes.
http://docs.mootools.net/files/Effects/Fx-Transitions-js.html</string>
			<key>match</key>
			<string>\b(linear|quadIn|quadOut|quadInOut|cubicIn|cubicOut|cubicInOut|quartIn|quartOut|quartInOut|quintIn|quintOut|quintInOut|sineIn|sineOut|sineInOut|expoIn|expoOut|expoInOut|circIn|circOut|circInOut|elasticIn|elasticOut|elasticInOut|backIn|backOut|backInOut|bounceIn|bounceOut|bounceInOut)\b</string>
			<key>name</key>
			<string>support.class.transitions.fx.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Fx.Utils
Contains Fx.Height, Fx.Width, Fx.Opacity.
http://docs.mootools.net/files/Effects/Fx-Styles-js.html</string>
			<key>match</key>
			<string>\b(toggle|show)\b</string>
			<key>name</key>
			<string>support.class.fx.utils.js.mootools</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(new)\s+(Fx\.(?:Height|Width|Opacity))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.new.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.instance.js.mootools</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.js</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.fx.utils.js.mootools</string>
			<key>end</key>
			<string>(\));?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.js</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dom-functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hash-functions</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.js</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>variable.parameter.fx.utils.options.js.mootools</string>
					<key>end</key>
					<string>(\})\)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.js</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(:)</string>
							<key>name</key>
							<string>punctuation.separator.key-value.js.mootools</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#fx-options</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Drag.Base
Modify two css properties of an element based on the position of the mouse.
http://docs.mootools.net/files/Drag/Drag-Base-js.html</string>
			<key>match</key>
			<string>\b(makeResizable)\b</string>
			<key>name</key>
			<string>support.class.element.js.mootools</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>
Drag.Move
Modify two css properties of an element based on the position of the mouse.
http://docs.mootools.net/files/Drag/Drag-Base-js.html</string>
			<key>match</key>
			<string>\b(makeDraggable)\b</string>
			<key>name</key>
			<string>support.class.element.js.mootools</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#leading-space</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array-functions</key>
		<dict>
			<key>begin</key>
			<string>(\$(?:each|A)\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.array.js.mootools</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.function.array.js.mootools</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.array.js.mootools</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.array.js.mootools</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>dom-functions</key>
		<dict>
			<key>begin</key>
			<string>(\$ES?\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.dom.js.mootools</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.function.dom.js.mootools</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.dom.js.mootools</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.dom.js.mootools</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>element-functions</key>
		<dict>
			<key>begin</key>
			<string>(\$?\$\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.element.js.mootools</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.function.element.js.mootools</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.element.js.mootools</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.element.js.mootools</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>fx-options</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(onStart|onComplete|transition|duration|unit|wait|fps)\b</string>
					<key>name</key>
					<string>support.class.keys.fx.options.js.mootools</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(mode)\b</string>
					<key>name</key>
					<string>support.class.keys.fx.slide.options.js.mootools</string>
				</dict>
			</array>
		</dict>
		<key>hash-functions</key>
		<dict>
			<key>begin</key>
			<string>(\$H\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.hash.js.mootools</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.function.hash.js.mootools</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.hash.js.mootools</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.hash.js.mootools</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>leading-space</key>
		<dict>
			<key>comment</key>
			<string>
The leading-space code is the ribbon highlighing thomas Aylott contributed to source.js.prototype.
More info in this thread:
http://comox.textdrive.com/pipermail/textmate/2006-August/012373.html
</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(?=(\t|  ))</string>
					<key>end</key>
					<string>(?=[^\t\s])</string>
					<key>name</key>
					<string>meta.leading-tabs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group1.spaces</string>
								</dict>
								<key>10</key>
								<dict>
									<key>name</key>
									<string>meta.even-tab.group10.spaces</string>
								</dict>
								<key>11</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group11.spaces</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>meta.even-tab.group2.spaces</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group3.spaces</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>meta.even-tab.group4.spaces</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group5.spaces</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>meta.even-tab.group6.spaces</string>
								</dict>
								<key>7</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group7.spaces</string>
								</dict>
								<key>8</key>
								<dict>
									<key>name</key>
									<string>meta.even-tab.group8.spaces</string>
								</dict>
								<key>9</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group9.spaces</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(  )(  )?(  )?(  )?(  )?(  )?(  )?(  )?(  )?(  )?(  )?</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group1.tab</string>
								</dict>
								<key>10</key>
								<dict>
									<key>name</key>
									<string>meta.even-tab.group10.tab</string>
								</dict>
								<key>11</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group11.tab</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>meta.even-tab.group2.tab</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group3.tab</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>meta.even-tab.group4.tab</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group5.tab</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>meta.even-tab.group6.tab</string>
								</dict>
								<key>7</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group7.tab</string>
								</dict>
								<key>8</key>
								<dict>
									<key>name</key>
									<string>meta.even-tab.group8.tab</string>
								</dict>
								<key>9</key>
								<dict>
									<key>name</key>
									<string>meta.odd-tab.group9.tab</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\t)(\t)?(\t)?(\t)?(\t)?(\t)?(\t)?(\t)?(\t)?(\t)?(\t)?</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.mootools</string>
	<key>uuid</key>
	<string>7E4B5859-2FB4-4D2A-9105-276BDE28B94E</string>
</dict>
</plist>
