<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s5</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--&gt;)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
		|^\s*--&gt;
		|(^|\s)\}
		)</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>S5 Slide Show</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.s5</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.s5</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.s5</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([A-Za-z0-9]+)(:)\s*(.*)$\n?</string>
			<key>name</key>
			<string>meta.header.s5</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?![A-Za-z0-9]+:)</string>
			<key>end</key>
			<string>^(?=not)possible$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^_{10}$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.separator.handout.s5</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>
						name = 'meta.separator.handout.s5';
						match = '(^_{10}$)';
					</string>
					<key>contentName</key>
					<string>text.html.markdown.handout.s5</string>
					<key>end</key>
					<string>(?=^(?:(?:✂-{6})+|^#{10})$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.markdown</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^#{10}$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.separator.notes.s5</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>
						name = 'meta.separator.notes.s5';
						match = '(^#{10}$)';
					</string>
					<key>contentName</key>
					<string>text.html.markdown.notes.s5</string>
					<key>end</key>
					<string>(?=^(?:(?:✂-{6})+|_{10})$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.markdown</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^((✂-{6})+$\n)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.separator.slide.s5</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>
						name = 'meta.separator.slide.s5';
						match = '^((✂-{6})+$\n)';
					</string>
					<key>contentName</key>
					<string>text.html.markdown.slide.s5</string>
					<key>end</key>
					<string>(?=^(?:(?:✂-{6})+|_{10}|#{10})$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.markdown</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.s5</string>
	<key>uuid</key>
	<string>84A2047B-4453-418D-B009-A3D3C60F3D1E</string>
</dict>
</plist>
