<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>
            This is a bundle for the Nu programming language (www.programming.nu)
        </string>
	<key>fileTypes</key>
	<array>
		<string>nu</string>
		<string>Nukefile</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\bnush\b</string>
	<key>foldingStartMarker</key>
	<string>\(</string>
	<key>foldingStopMarker</key>
	<string>\)</string>
	<key>keyEquivalent</key>
	<string>^~N</string>
	<key>name</key>
	<string>Nu</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(t|nil|self|super|YES|NO|margs)\b</string>
			<key>name</key>
			<string>constant.language.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|-?(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.nu</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(')(.|\\[nrfbaes]|\\[0-7]{3}|\\x\h{2}|\\u\h{4})(')</string>
			<key>name</key>
			<string>constant.character.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@)[a-zA-Z_]\w*</string>
			<key>name</key>
			<string>variable.other.readwrite.instance.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$)[a-zA-Z_]\w*</string>
			<key>name</key>
			<string>variable.other.readwrite.global.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z]\w*\b</string>
			<key>name</key>
			<string>support.class.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.hash.nu</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>-"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nu</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nu</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.unescaped.nu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolated_nu</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\+?"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nu</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nu</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.escaped.nu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_nu</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;&lt;[+](.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nu</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\1</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nu</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.unquoted.heredoc.escaped.nu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_nu</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;&lt;[-](.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nu</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\1</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nu</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.unquoted.heredoc.unescaped.nu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolated_nu</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(/)(?=[^ ])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.regex.begin.nu</string>
				</dict>
			</dict>
			<key>end</key>
			<string>/[isxlm]*</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.regex.end.nu</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.regexp.nu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\/</string>
					<key>name</key>
					<string>constant.character.escape.nu</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.class.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.is.nu</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(class)\s+((\w|\-|\!|\?)*)(\s+(is)\s+((\w|\-|\!|\?)*))?</string>
			<key>name</key>
			<string>meta.class.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.protocol.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(protocol)\s+((\w)*)</string>
			<key>name</key>
			<string>meta.protocol.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\((import)\s+(\w*)</string>
			<key>name</key>
			<string>meta.import.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.global.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.readwrite.global.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\((global)\s+([\w\-]*)</string>
			<key>name</key>
			<string>meta.global.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.method.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.is.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\(([+-]|[ic]method)\s+\((\w+)\)\s+(\w+)\s+(is)</string>
			<key>name</key>
			<string>meta.method.nu.zero-args</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.method.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.nu</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.control.is.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\(([+-]|[ic]method)\s+\((\w+)\)\s+(\w+\:)\s*\((\w+)\)\s+(\w+)\s+(is)</string>
			<key>name</key>
			<string>meta.method.nu.one-arg</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.method.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.nu</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.nu</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>keyword.control.is.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\(([+-]|[ic]method)\s+\((\w+)\)\s+(\w+\:)\s*\((\w+)\)\s+(\w+)\s+(\w+\:)\s*\((\w+)\)\s+(\w+)\s+(is)</string>
			<key>name</key>
			<string>meta.method.nu.two-args</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.method.nu</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.nu</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>keyword.control.is.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.nu</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nu</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.nu</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\(([+-]|[ic]method)\s+\((\w+)\)\s+(\w+\:)\s*\((\w+)\)\s+(\w+)\s+(\w+\:)\s*\((\w+)\)\s+(\w+)\s+(\w+\:)\s*\((\w+)\)\s+(\w+)\s+(is)</string>
			<key>name</key>
			<string>meta.method.nu.three-args</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.class.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.class.nu</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((ivar)\s+((\w|\-|\!|\?)*)(\s+(is)\s+((\w|\-|\!|\?)*))?|ivars|ivar-accessors)</string>
			<key>name</key>
			<string>meta.ivars.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.function-type.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(function|macro|macro-0)\s+((\w|\-|\!|\?)*)</string>
			<key>name</key>
			<string>meta.function.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.task.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.nu</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.colon.nu</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.description.task.nu</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.is.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(task)\s+(\"\w+")\s?(:?)\s?(\"\w+\")?\s+(is)</string>
			<key>name</key>
			<string>meta.nukefile.task.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.task.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.nu</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.colon.nu</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.description.task.nu</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.arrow.nu</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.dependency.task.nu</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.control.is.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(task)\s+(\"\w+\")\s?(:)?\s?(\".+\")?\s?(=&gt;?)\s?(\"[\"\w\s]+\")?\s+(is)</string>
			<key>name</key>
			<string>meta.nukefile.task.with-dependencies.nu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.task.nu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.nu</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.arrow.nu</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.name.task.nu</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.is.nu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(task)\s+(\"default\")\s+(=&gt;)\s+(\"\w+\")</string>
			<key>name</key>
			<string>meta.nukefile.default.task.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(let|set|cond|case|do|loop|until|while|for|break|continue|if|else|elseif|then|unless|try|throw|catch|array|dict|list|return)\b</string>
			<key>name</key>
			<string>keyword.control.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(eq|neq|and|or|synchronized|not)\b</string>
			<key>name</key>
			<string>keyword.operator.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[/*+-/&amp;|&gt;&lt;=!]</string>
			<key>name</key>
			<string>keyword.operator.symbolic.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(append|atom|cons|car|cdr|context|eval|head|quote|parse|progn|send|tail|load|system|puts|help|version|beep|first|rest)\b</string>
			<key>name</key>
			<string>support.function.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(assert_equal|assert_not_equal|assert_throws|assert_in_delta|assert_true|assert_false|assert_less_than|assert_greater_than)\b</string>
			<key>name</key>
			<string>support.function.testing.nu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(task|application-tasks|bundle-tasks|compilation-tasks|dylib-tasks|framework-tasks|library-tasks)\b</string>
			<key>name</key>
			<string>keyword.nukefile.nu</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\([0-7]{3}|x\h{2}|u\h{4}|.)</string>
			<key>name</key>
			<string>constant.character.escape.nu</string>
		</dict>
		<key>interpolated_nu</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.nu</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.nu.embedded.source.empty</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#\{(\})</string>
					<key>name</key>
					<string>source.nu.embedded.source</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>#\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.nu</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>source.nu.embedded.source</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.nu</string>
	<key>uuid</key>
	<string>F8A96494-C89A-4CA4-A2D3-6A5A4ED56FD7</string>
</dict>
</plist>
