<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sce</string>
		<string>sci</string>
		<string>tst</string>
		<string>dem</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^(?!.*//.*).*\b(if|while|for|function|select)\b</string>
	<key>foldingStopMarker</key>
	<string>\b(endfunction|end)\b</string>
	<key>name</key>
	<string>Scilab</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.scilab</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.scilab</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(%inf|%i|%pi|%eps|%e|%nan|%s|%t|%f)\b</string>
			<key>name</key>
			<string>support.constant.scilab</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"(?!")</string>
			<key>name</key>
			<string>string.quoted.double.scilab</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>''|""</string>
					<key>name</key>
					<string>constant.character.escape.scilab</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;![\w\]\)])'</string>
			<key>end</key>
			<string>'(?!')</string>
			<key>name</key>
			<string>string.quoted.single.scilab</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>''|""</string>
					<key>name</key>
					<string>constant.character.escape.scilab</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.scilab</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.scilab</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(function)\s+(?:[^=]+=\s*)?(\w+)(?:\s*\(.*\))?</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|elseif|while|for|function|end|endfunction|return|select|case|break|global)\b</string>
			<key>name</key>
			<string>keyword.control.scilab</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.\.\.\s*$</string>
			<key>name</key>
			<string>punctuation.separator.continuation.scilab</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.scilab</string>
	<key>uuid</key>
	<string>14374AA3-A329-4623-8DFA-1ACC2CE222B9</string>
</dict>
</plist>
