<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>defs.rem</string>
		<string>REM*.txt</string>
		<string>.reminders</string>
	</array>
	<key>firstLineMatch</key>
	<string>^REM*</string>
	<key>name</key>
	<string>Remind</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.remind</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[ ]*(#).*\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.remind</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.remind</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[ ]*(;).*\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.remind</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.single.command.remind</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(?:RUN\s+(ON|OFF))|(PUSH|CLEAR|POP)-OMIT-CONTEXT)\b</string>
			<key>name</key>
			<string>meta.single.command.remind</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?i:(SET))\s+(\$?\w+)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.set.setline.remind</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.setline.remind</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=#|\n|\z)</string>
			<key>name</key>
			<string>meta.setline.remind</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?i:(FSET))\s+(\w+(\())(\w+)?(?:,(\w+))*(\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.fset.fsetline.remind</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fsetline.remind</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.remind</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fsetline.remind</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fsetline.remind</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.remind</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=#|\n|\z)</string>
			<key>name</key>
			<string>meta.fsetline.remind</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?i:(UNSET))\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.set.unsetline.remind</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=#|\n|\z)</string>
			<key>name</key>
			<string>meta.unsetline.remind</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b\w+\b</string>
					<key>name</key>
					<string>variable.other.unsetline.remind</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?i:(IF))\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.if.remind</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=#|\n|\z)</string>
			<key>name</key>
			<string>meta.if.remind</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?i:(IFTRIG))\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.iftrig.remind</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=#|\n|\z)</string>
			<key>name</key>
			<string>meta.iftrig.remind</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#trigger</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(ELSE|ENDIF))\s*(?=#|\n|\z)</string>
			<key>name</key>
			<string>keyword.control.else-or-endif.remind</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?i:INCLUDE)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.include.commandline.remind</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=#|\n|\z)</string>
			<key>name</key>
			<string>meta.includeline.remind</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?i:REM|OMIT|BANNER)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.command.commandline.remind</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(%?[ \t]*)(?=(#|\n|\z))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.endline.commandline.remind</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.commandline.remind</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:SCHED|WARN|SCANFROM|SCAN|UNTIL)\b</string>
					<key>name</key>
					<string>keyword.control.expiry.commandline.remind</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(?i:SATISFY)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.satisfy.commandline.remind</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=(#|\n|\z))</string>
					<key>name</key>
					<string>meta.satisfy.remind</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#trigger</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#message-body</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracketed-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#message</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#bracketed-expression</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#message</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bracketed-expression</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.remind</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>date-item</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:January|Jan|February|Feb|March|Mar|April|Apr|May|June|Jun|July|Jul|August|Aug|September|Sep|October|Oct|November|Nov|December|Dec)\b</string>
					<key>name</key>
					<string>support.constant.month.dateitem.remind</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:Monday|Mon|Tuesday|Tue|Wednesday|Wed|Thursday|Thu|Friday|Fri|Saturday|Sat|Sunday|Sun)\b</string>
					<key>name</key>
					<string>support.constant.weekday.dateitem.remind</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:\d{1,2})\b</string>
					<key>name</key>
					<string>support.constant.day.dateitem.remind</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:\d{4})\b</string>
					<key>name</key>
					<string>support.constant.year.dateitem.remind</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.remind</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>-|\*|/|%|\+|-|[!&lt;&gt;=]=?|&amp;&amp;|\|\|</string>
					<key>name</key>
					<string>keyword.operator.remind</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.remind</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.remind</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.remind</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.remind</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>'\d{4}([\-/])\d{1,2}\1\d{1,2}'</string>
					<key>name</key>
					<string>constant.other.date.remind</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\d{1,2}[:.]\d{2}</string>
					<key>name</key>
					<string>constant.other.time.remind</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>constant.numeric.integer.remind</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$(?:CalcUTC|CalMode|Daemon|DefaultPrio|DontFork|DontTrigAts|DontQueue|EndSent|EndSentIg|FirstIndent|FoldYear|FormWidth|HushMode|IgnoreOnce|InfDelta|LatDeg|LatMin|LatSec|Location|LongDeg|LongMin|LongSec|MaxSatIter|MinsFromUTC|NextMode|NumQueued|NumTrig|PrefixLineNo|PSCal|RunOff|SimpleCal|SortByDate|SortByPrio|SortByTime|SubsIndent)\b</string>
					<key>name</key>
					<string>variable.language.system.remind</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(?:abs|access|args|asc|baseyr|char|choose|coerce|date|dawn|day|daysinmon|defined|dosubst|dusk|easterdate|filedate|filedir|filename|getenv|hour|iif|index|isdst|isleap|isomitted|hebdate|hebday|hebmon|hebyear|language|lower|max|min|minsfromutc|minute|min|monnum|moondate|moontime|moonphase|now|ord|ostype|plural|psmoon|psshade|realnow|realtoday|sgn|shell|strlen|substr|sunrise|sunset|time|today|trigdate|trigger|trigtime|trigvalid|typeof|upper|value|version|wkday|wkdaynum|year)\(</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.function.builtin.remind</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.function.builtin.remind</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(\w+)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.remind</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.remind</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.remind</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.user.remind</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\w+\b</string>
					<key>name</key>
					<string>variable.parameter.user.remind</string>
				</dict>
			</array>
		</dict>
		<key>message</key>
		<dict>
			<key>begin</key>
			<string>\b(?i:MSG|MSF|RUN|CAL|SPECIAL|PS|PSFILE)\b\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.message.commandline.remind</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(%?[ \t]*)(?=\n|\z)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.endline.commandline.remind</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#message-body</string>
				</dict>
			</array>
		</dict>
		<key>message-body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.remind</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(%)[a-zA-Z0-9_!@#]</string>
					<key>name</key>
					<string>constant.other.placeholder.remind</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>%"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.remind</string>
						</dict>
					</dict>
					<key>end</key>
					<string>%"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.remind</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.remind</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracketed-expression</string>
				</dict>
			</array>
		</dict>
		<key>trigger</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.attime.trigger.remind</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.time.trigger.remind</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.component.trigger.remind</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.other.comp.trigger.remind</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?i:(AT))\s+(\d{1,2}[:.]\d{2})(?:\s+(\+{1,2}\d+))?(?:\s+(\*\d+))?(?=\s)</string>
					<key>name</key>
					<string>meta.attime.trigger.remind</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.duration.trigger.remind</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.time.trigger.remind</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?i:(DURATION))\s+(\d{1,2}[:.]\d{2})(?=\s)</string>
					<key>name</key>
					<string>meta.duration.trigger.remind</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:OMIT)\b</string>
					<key>name</key>
					<string>keyword.control.command.trigger.remind</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:ONCE|SKIP|BEFORE|AFTER)\b</string>
					<key>name</key>
					<string>keyword.control.move-reminder.trigger.remind</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.remind</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\+{1,2})\d+</string>
					<key>name</key>
					<string>variable.other.component.delta.trigger.remind</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.remind</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\-{1,2})\d+</string>
					<key>name</key>
					<string>variable.other.component.back.trigger.remind</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.remind</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\*)\d+</string>
					<key>name</key>
					<string>variable.other.component.repeat.trigger.remind</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date-item</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.remind</string>
	<key>uuid</key>
	<string>8D255A1E-9CBC-4B22-8AAD-F8536C276727</string>
</dict>
</plist>
