<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gsp</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl|g:javascript)\b.*?&gt;
		|&lt;!--(?!.*--&gt;)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl|g:javascript)&gt;
		|^\s*--&gt;
		|(^|\s)\}
		)</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>Grails Server Page</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;%+(?!&gt;)=?</string>
			<key>end</key>
			<string>%&gt;</string>
			<key>name</key>
			<string>source.groovy.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.groovy</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?&lt;((?i:g:javascript))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=&lt;/(g:javascript|g:javascript))&gt;(?:\s*\n)?</string>
			<key>name</key>
			<string>source.js.embedded.gsp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!&lt;/(?:g:javascript))&gt;</string>
					<key>end</key>
					<string>&lt;/((?i:g:javascript))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>//.*?((?=&lt;/g:javascript)|$\n?)</string>
							<key>name</key>
							<string>comment.line.double-slash.js</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>/\*</string>
							<key>end</key>
							<string>\*/|(?=&lt;/g:javascript)</string>
							<key>name</key>
							<string>comment.block.js</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.grails</string>
	<key>uuid</key>
	<string>E4DECA1B-424C-4A75-AD67-E907F182E4FB</string>
</dict>
</plist>
