<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gtd</string>
		<string>gtdlog</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*project</string>
	<key>foldingStopMarker</key>
	<string>^\s*end\s*$</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>GTDalt</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.project.begin.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.project.title.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(project)\s+(.*)</string>
			<key>name</key>
			<string>meta.project.begin.gtdalt</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.project.end.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(end)\s*</string>
			<key>name</key>
			<string>meta.project.end.gtdalt</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.action.context.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.action.title.gtdalt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.action.note.gtdalt</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.action.note.gtdalt</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.timestamp.action.due.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(@\S+)\s+(?:([^\[]+)(?:\s+)(?:(\[\d+\]))?(?:\s*)(?:(due:)(\[\d{4}-\d{2}-\d{2}\]))?\s*+)?</string>
			<key>name</key>
			<string>meta.action.gtdalt</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.action.completed.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.timestamp.action.completed.gtdalt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.action.completed.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(#completed:)(\[\d{4}-\d{2}-\d{2}\])\s*(.*)</string>
			<key>name</key>
			<string>meta.action.completed.gtdalt</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.note.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\[\d+\])\s*(.*)\n?</string>
			<key>name</key>
			<string>meta.note.gtdalt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*</string>
			<key>name</key>
			<string>meta.emptyline.gtdalt</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.timestamp.action.archived.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.project.action.archived.gtdalt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.context.action.archived.gtdalt</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.action.archived.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\/(\d{4}-\d{2}-\d{2})\/([^\/]+)\/(@\S+)\s++(.*)$</string>
			<key>name</key>
			<string>meta.action.archived.gtdalt</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.timestamp.project.archived.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.project.archived.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\/(\d{4}-\d{2}-\d{2})\/([^\/]+)$</string>
			<key>name</key>
			<string>meta.project.archived.gtdalt</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.gtdalt</string>
	<key>uuid</key>
	<string>C36472BD-A8CD-4613-A595-CEFB052E6181</string>
</dict>
</plist>
