<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gtd</string>
		<string>gtdlog</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*project</string>
	<key>foldingStopMarker</key>
	<string>^\s*end\s*$</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>GTDalt</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*(project)\s+(.*)(\n)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.line.project.begin.gtdalt</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.project.begin.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.project.title.gtdalt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.project.newline.gtdalt</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s*(end)\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.line.project.end.gtdalt</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.project.end.gtdalt</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.project.begin.gtdalt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*((@)\S++)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.context.action.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.context.action.gtdalt</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.action.gtdalt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#note</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#title</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.action.completed.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation..definition.completed.gtdalt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation..definition.completed.gtdalt</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other.timestamp.action.completed.gtdalt</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.date.gtdalt</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.date.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((#)completed(:))((\[)\d{4}-\d{2}-\d{2}(\]))\s*(.*)</string>
			<key>name</key>
			<string>meta.action.completed.gtdalt</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((\[)\d+(\]))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.other.note.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.note.note.gtdalt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.note.note.gtdalt</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.note.gtdalt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.archived.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other.timestamp.action.archived.gtdalt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.archived.gtdalt</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.other.project.action.archived.gtdalt</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.archived.gtdalt</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type.context.action.archived.gtdalt</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>comment.line.slash.action.archived.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\/)(\d{4}-\d{2}-\d{2})(\/)([^\/]+)(\/)(@\S+)\s++(.*)$</string>
			<key>name</key>
			<string>meta.action.archived.gtdalt</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.archived.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other.timestamp.project.archived.gtdalt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.archived.gtdalt</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.other.project.archived.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\/)(\d{4}-\d{2}-\d{2})(\/)([^\/]+)$</string>
			<key>name</key>
			<string>meta.project.archived.gtdalt</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(#)\s+.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.generic.gtdalt</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>date</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.due.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.valuepair.due.gtdalt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other.timestamp.due.gtdalt</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.due.gtdalt</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.due.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((?:due|at|from)(:))((\[)\d{4}-\d{2}-\d{2}(\]))</string>
		</dict>
		<key>link</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.gtdalt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;)([^&gt;]*)(&gt;)</string>
		</dict>
		<key>note</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.note.gtdalt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.note.gtdalt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)\d+(\])</string>
			<key>name</key>
			<string>support.other.note.gtdalt</string>
		</dict>
		<key>title</key>
		<dict>
			<key>match</key>
			<string>\S+(?:\s+\S+)*?(?=\s*(?:\[\d+\]|(?:due|at|from):|$))</string>
			<key>name</key>
			<string>constant.other.title.gtdalt</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.gtdalt</string>
	<key>uuid</key>
	<string>C36472BD-A8CD-4613-A595-CEFB052E6181</string>
</dict>
</plist>
