// _dateInterval_EOArchive.java
// Generated by EnterpriseObjects palette at Friday, November 3, 2006 9:07:29 PM America/Indianapolis

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _dateInterval_EOArchive extends com.webobjects.eoapplication.EOArchive {
    ObjectController _objectController0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2;
    com.webobjects.eointerface.swing.EOView _nsDatePicker0, _nsStepper0;
    javax.swing.JComboBox _popup0, _popup1, _popup2;
    javax.swing.JPanel _nsView0;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1, _jRadioButton2;

    public _dateInterval_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _objectController0 = (ObjectController)_registered(new ObjectController(), "NSObjectController");
        _popup2 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton11");
        _popup1 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton1");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111");
        _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        _nsStepper0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSCustomView");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");
        _jRadioButton2 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton(""), "");
        _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton(""), "");
        _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton(""), "");
        _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(3, 1, 4, 2), "NSMatrix1");
        _nsDatePicker0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View1");
        _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _popup2.setModel(new javax.swing.DefaultComboBoxModel());
        _popup2.addItem("Monday");
        _popup2.addItem("Tuesday");
        _popup2.addItem("Wednesday");
        _popup2.addItem("Thursday");
        _popup2.addItem("Friday");
        _popup2.addItem("Saturday");
        _popup2.addItem("Sunday");
        _popup1.setModel(new javax.swing.DefaultComboBoxModel());
        _popup1.addItem("this upcoming");
        _popup1.addItem("one week after upcoming");
        _popup1.addItem("two weeks after upcoming");
        _popup0.setModel(new javax.swing.DefaultComboBoxModel());
        _popup0.addItem("Days");
        _popup0.addItem("Weeks");
        _popup0.addItem("Months");
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_popup2, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_popup1, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsTextField2, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("from today");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_popup0, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField1.setEditable(true);
        _nsTextField1.setOpaque(true);
        _nsTextField1.setText("");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(true);
        _nsTextField1.setEnabled(true);
        _setFontForComponent(_nsTextField0, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("on");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        _setFontForComponent(_jRadioButton2, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton1, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton0, "Lucida Grande", 13, Font.PLAIN);
        _jRadioButton0.setSize(24, 18);
        _jRadioButton0.setLocation(0, 0);
        _nsMatrix0.add(_jRadioButton0);
        _jRadioButton1.setSize(24, 18);
        _jRadioButton1.setLocation(0, 20);
        _nsMatrix0.add(_jRadioButton1);
        _jRadioButton2.setSize(24, 18);
        _jRadioButton2.setLocation(0, 40);
        _nsMatrix0.add(_jRadioButton2);
        _setFontForComponent(_nsMatrix0, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_nsDatePicker0, "Lucida Grande", 13, Font.PLAIN);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsDatePicker0.setSize(139, 27);
        _nsDatePicker0.setLocation(49, 29);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsDatePicker0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsDatePicker0);
        _nsMatrix0.setSize(24, 58);
        _nsMatrix0.setLocation(11, 13);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix0);
        _nsTextField0.setSize(23, 13);
        _nsTextField0.setLocation(32, 37);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsTextField1.setSize(30, 19);
        _nsTextField1.setLocation(34, 12);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsStepper0.setSize(15, 22);
        _nsStepper0.setLocation(63, 11);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsStepper0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsStepper0);
        _popup0.setSize(74, 22);
        _popup0.setLocation(78, 11);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsView0.add(_popup0);
        _nsTextField2.setSize(80, 13);
        _nsTextField2.setLocation(160, 15);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);
        _popup1.setSize(164, 22);
        _popup1.setLocation(24, 53);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup1, EOViewLayout.MinYMargin);
        _nsView0.add(_popup1);
        _popup2.setSize(74, 22);
        _popup2.setLocation(186, 53);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup2, EOViewLayout.MinYMargin);
        _nsView0.add(_popup2);
        _nsView0.setSize(280, 95);
        _eoFrame0.setTitle("Window");
        _eoFrame0.setLocation(433, 446);
        _eoFrame0.setSize(280, 95);
    }
}
