<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>n</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(\{|(|&lt;\[)</string>
	<key>foldingStopMarker</key>
	<string>(\}|)|]&gt;)</string>
	<key>keyEquivalent</key>
	<string>^~N</string>
	<key>name</key>
	<string>Nemerle</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nemerle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.nemerle</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nemerle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.nemerle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(|false|null|true)\b</string>
			<key>name</key>
			<string>constant.language.nemerle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(([0-9]+(\.|\_)?[0-9]*(b|bu|d|f|L|LU|m|u|ub|UL)?)|(0(b|o|x)[0-9]+))\b</string>
			<key>name</key>
			<string>constant.numeric.nemerle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(catch|else|finally|for|foreach|if|match|repeat|try|unless|when|while)\b</string>
			<key>name</key>
			<string>keyword.control.nemerle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+|\-|\*|\/|\%)\=?</string>
			<key>name</key>
			<string>keyword.operator.nemerle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\_|as|assert|base|checked|do|fun|get|ignore|implements|in|is|lock|namespace|out|params|ref|set|syntax|throw|typeof|unchecked|using|with)\b</string>
			<key>name</key>
			<string>keyword.other.nemerle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(array|bool|byte|char|class|decimal|double|enum|float|int|interface|list|long|macro|module|object|sbyte|short|string|struct|type|uint|ulong|ushort|variant|void)\b</string>
			<key>name</key>
			<string>storage.type.nemerle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abstract|def|delegate|event|extern|internal|mutable|override|public|private|protected|sealed|static|volatile|virtual|new)\b</string>
			<key>name</key>
			<string>storage.modifier.nemerle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>this</string>
			<key>name</key>
			<string>variable.language.nemerle</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nemerle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nemerle</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.nemerle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|'|\"|a|b|c[A-Z]+|e|f|n|r|u0+[0-9,A-Z]+|v)</string>
					<key>name</key>
					<string>constant.character.escape.nemerle</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nemerle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nemerle</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.interpolated.nemerle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\$[a-z,A-Z]+[a-z,A-Z,0-9]*( |\+|\-|\*|\/|\%)</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nemerle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nemerle</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.nemerle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|'|\"|a|b|c[A-Z]+|e|f|n|r|u0+[0-9,A-Z]+|v)</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nemerle</string>
	<key>uuid</key>
	<string>F563968D-4CB3-11DB-9F95-00112474B8F0</string>
</dict>
</plist>
