<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>todo</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>Taskmate</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*(\w+.+:\s*$\n?)</string>
			<key>name</key>
			<string>keyword.control.header.taskmate</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bullet.completed.taskmate</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.completed.taskmate</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\+|✓)\s+((?:[^\@]|(?&lt;!\s)\@|\@(?=\s))*)</string>
			<key>name</key>
			<string>meta.item.taskmate.completed</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bullet.pending.taskmate</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>text.pending.taskmate</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(-)\s+((?:[^\@]|(?&lt;!\s)\@)*)</string>
			<key>name</key>
			<string>meta.item.taskmate.pending</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s)\@(?!today|completed)[\w\d\-!?]+\s?</string>
			<key>name</key>
			<string>meta.tag.taskmate</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s)\@completed \([\d\.:\-/ ].+\)\s?</string>
			<key>name</key>
			<string>meta.tag.taskmate.completed</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s)\@today\s?</string>
			<key>name</key>
			<string>string.other.tag.taskmate.today</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.taskmate</string>
	<key>uuid</key>
	<string>3020100E-153C-45EF-ACA3-4C44E7D92A30</string>
</dict>
</plist>
