intrinsic class System.capabilities
{
	static var hasAudio:Boolean;
	static var hasMP3:Boolean;
	static var hasAudioEncoder:Boolean;
	static var hasVideoEncoder:Boolean;
	static var screenResolutionX:Number;
	static var screenResolutionY:Number;
	static var screenDPI:Number;
	static var screenColor:String;
	static var pixelAspectRatio:Number;
	static var hasAccessibility:Boolean;
	static var input:String;
	static var isDebugger:Boolean;
	static var language:String;
	static var manufacturer:String;
	static var os:String;
	static var serverString:String;
	static var version:String;
	static var hasPrinting:Boolean;
	static var playerType:String;
	static var hasStreamingAudio:Boolean;
	static var hasScreenBroadcast:Boolean;
	static var hasScreenPlayback:Boolean;
	static var hasStreamingVideo:Boolean;
	static var hasEmbeddedVideo:Boolean;
	static var avHardwareDisable:Boolean;
	static var localFileReadDisable:Boolean;
	static var windowlessDisable:Boolean;
}
