<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>Ant</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;)([a-zA-Z0-9]+)(:)([a-zA-Z0-9]+)(?=[^&gt;]*&gt;&lt;/mx:\4&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml.ant</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.namespace.xml.ant</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.namespace.xml.ant</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml.ant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;(&lt;)/)([a-zA-Z0-9]+)(:)(\4)(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml.ant</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.scope.between-tag-pair.xml.ant</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.namespace.xml.ant</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.namespace.xml.ant</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml.ant</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml.ant</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.xml.ant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.xml.ant</string>
	<key>uuid</key>
	<string>E1B78601-E584-4A7F-B011-A61710BFE035</string>
</dict>
</plist>
