<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ldif</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^r?dn:</string>
	<key>foldingStopMarker</key>
	<string>^$</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>LDIF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^r?dn:.*$</string>
			<key>name</key>
			<string>entity.distinguishedName.ldif</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?=[^#])\w+:[:&lt;]?</string>
			<key>name</key>
			<string>keyword.attribute.ldif</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\w:\s)</string>
			<key>end</key>
			<string>(?=^[\S\n])</string>
			<key>name</key>
			<string>string.value.ldif</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s+(?=\n)</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\w::\s)</string>
			<key>end</key>
			<string>(?=^[\S\n])</string>
			<key>name</key>
			<string>storage.value.base64.ldif</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s+(?=\n)</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=:&lt;\s)</string>
			<key>end</key>
			<string>(?=^[\S\n])</string>
			<key>name</key>
			<string>markup.underline.link.ldif</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s+(?=\n)</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.ldif</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^-$\n?</string>
			<key>name</key>
			<string>support.separator.ldif</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.ldif</string>
	<key>uuid</key>
	<string>D8D20662-03C0-4303-A431-EB2427D97F0F</string>
</dict>
</plist>
