<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pmwiki</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>PmWiki</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&gt;&gt;comment&lt;&lt;</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pmwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;&gt;&lt;&lt;</string>
			<key>name</key>
			<string>comment.block.pmwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&gt;&gt;</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.pmwiki</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%comment%</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pmwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.pmwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.pmwiki</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\\\\$</string>
			<key>name</key>
			<string>keyword.control.line-break.pmwiki</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[\[&lt;&lt;\]\]</string>
			<key>name</key>
			<string>keyword.control.line-break.pmwiki</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\$</string>
			<key>name</key>
			<string>keyword.control.continue-line.pmwiki</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s+</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.raw.monospace.pmwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.pmwiki</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(-+&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.indented-paragraph.pmwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.indented-paragraph.pmwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.pmwiki</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(!+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.heading.pmwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.heading.pmwiki</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\*+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.bullet-list.pmwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.list.unnumbered.pmwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.pmwiki</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(#+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.number-list.pmwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.list.numbered.pmwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.pmwiki</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.term-definition.pmwiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.term.pmwiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.term-definition.pmwiki</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.definition.pmwiki</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(:+)(.*)(:)(.*)$</string>
			<key>name</key>
			<string>meta.term-definition.pmwiki</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^-{4,}.*$</string>
			<key>name</key>
			<string>meta.separator.pmwiki</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'''</string>
			<key>end</key>
			<string>'''</string>
			<key>name</key>
			<string>markup.bold.strong.pmwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.pmwiki</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>''</string>
			<key>end</key>
			<string>''(?!')</string>
			<key>name</key>
			<string>markup.italic.emphasis.pmwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.pmwiki</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>@@</string>
			<key>end</key>
			<string>@@</string>
			<key>name</key>
			<string>markup.raw.monospace.pmwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.pmwiki</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[\+</string>
			<key>end</key>
			<string>\+\]</string>
			<key>name</key>
			<string>meta.style.larger.pmwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.pmwiki</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[-</string>
			<key>end</key>
			<string>-\]</string>
			<key>name</key>
			<string>meta.style.smaller.pmwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.pmwiki</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>`\w+</string>
			<key>name</key>
			<string>meta.normal-word.pmwiki</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\u\w+\u\w+</string>
			<key>name</key>
			<string>markup.underline.pmwiki</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[\[#</string>
			<key>contentName</key>
			<string>string.other.link.title.pmwiki</string>
			<key>end</key>
			<string>\]\]</string>
			<key>name</key>
			<string>meta.link.inline.pmwiki</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.pmwiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.link.pmwiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.pmwiki</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[\[(.*?)\s*(\||-&gt;)\s*(.*?)\]\]</string>
			<key>name</key>
			<string>meta.link.inline.pmwiki</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.pmwiki</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[\[(.*?)\]\]</string>
			<key>name</key>
			<string>meta.link.inline.pmwiki</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[=</string>
			<key>end</key>
			<string>=\]</string>
			<key>name</key>
			<string>markup.raw.verbatim-text.pmwiki</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.pmwiki</string>
	<key>uuid</key>
	<string>B991CA22-EE93-410C-A4EB-7578D9CE6C8D</string>
</dict>
</plist>
