<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>moinmoin</string>
	</array>
	<key>name</key>
	<string>MoinMoin</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*=\s.*\s=\n</string>
			<key>name</key>
			<string>markup.heading.1.moinmoin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*==\s.*\s==\n</string>
			<key>name</key>
			<string>markup.heading.2.moinmoin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*===\s.*\s===\n</string>
			<key>name</key>
			<string>markup.heading.3.moinmoin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*====\s.*\s====\n</string>
			<key>name</key>
			<string>markup.heading.4.moinmoin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*=====\s.*\s=====\n</string>
			<key>name</key>
			<string>markup.heading.5.moinmoin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*-----\s*\n</string>
			<key>name</key>
			<string>meta.separator.moinmoin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#pragma.*</string>
			<key>name</key>
			<string>meta.pragma.moimoin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^##.*</string>
			<key>name</key>
			<string>comment.line.double-number-sign.moimoin</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s+(\*)(\s)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.list-item-marker</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.list.unnumbered.moinmoin</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.list.unnumbered.moinmoin</string>
			<key>end</key>
			<string>\n</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s+((?:[aAiI]|\d+)\.(?:\#\d+)?)(\s)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.list-item-marker</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.list.numbered.moinmoin</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.list.numbered.moinmoin</string>
			<key>end</key>
			<string>\n</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(\|\|)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.table.column.moinmoin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.table.column.moinmoin</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.table.moinmoin</string>
			<key>end</key>
			<string>(\|\|$)|\n</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?=\S)</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.paragraph.moinmoin</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{{3}(?!.*\}{3})</string>
					<key>end</key>
					<string>\}{3}</string>
					<key>name</key>
					<string>markup.raw.block.moinmoin</string>
				</dict>
				<dict>
					<key>match</key>
					<string>`[^`]*`|{{{.*?}}}</string>
					<key>name</key>
					<string>markup.raw.inline.moinmoin</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'{2}(?='{3}[^']*'{3})</string>
					<key>contentName</key>
					<string>markup.italic.moinmoin</string>
					<key>end</key>
					<string>'{2}(?!')|'{2}(?='{3})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'{3}</string>
					<key>contentName</key>
					<string>markup.bold.moinmoin</string>
					<key>end</key>
					<string>'{3}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'{2}</string>
					<key>contentName</key>
					<string>markup.italic.moinmoin</string>
					<key>end</key>
					<string>'{2}(?!')|'{2}(?='{3})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>__</string>
					<key>contentName</key>
					<string>markup.underline.moinmoin</string>
					<key>end</key>
					<string>__</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\!)/?(?:[A-Z][a-z0-9]+[A-Z][a-z0-9]+[A-Za-z0-9]*)</string>
					<key>name</key>
					<string>markup.underline.link.moinmoin</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[".*?"\]</string>
					<key>name</key>
					<string>markup.underline.link.moinmoin</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[:.*?:.*?\]</string>
					<key>name</key>
					<string>markup.underline.link.moinmoin</string>
				</dict>
				<dict>
					<key>match</key>
					<string>https?://\S+</string>
					<key>name</key>
					<string>markup.underline.link.moinmoin</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[https?://.*?\]</string>
					<key>name</key>
					<string>markup.underline.link.moinmoin</string>
				</dict>
				<dict>
					<key>match</key>
					<string>attachment:\S+</string>
					<key>name</key>
					<string>markup.underline.link.moinmoin</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|\|</string>
					<key>name</key>
					<string>meta.table.column.moinmoin</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[\[.*?\]\]</string>
					<key>name</key>
					<string>meta.macro.moinmoin</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.moinmoin</string>
	<key>uuid</key>
	<string>DB315CBC-23FD-4952-9D64-F2AC0618A840</string>
</dict>
</plist>
