<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>This is a wrapper for and adds nested bracket scopes to Prototype &amp; Script.aculo.us (JavaScript). It also allow for embedded ruby source. By Thomas Aylott</string>
	<key>foldingStartMarker</key>
	<string>(\{[^\}]*$|\([^\)]*$|&lt;%)</string>
	<key>foldingStopMarker</key>
	<string>(^[^\{]*\}|^\s*\)|%&gt;)</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>Prototype &amp; Script.aculo.us (JavaScript) Rails</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;%=</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.js</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.source.embedded.return-value</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=&lt;%=)</string>
					<key>end</key>
					<string>(?=%&gt;)</string>
					<key>name</key>
					<string>source.ruby.rails.embedded.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby.rails</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%(?![=#])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.js</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.source.embedded</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=&lt;%)</string>
					<key>end</key>
					<string>(?=%&gt;)</string>
					<key>name</key>
					<string>source.ruby.rails.embedded.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby.rails</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js.prototype</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js.prototype.bracketed</string>
	<key>uuid</key>
	<string>1FD22341-8BAA-4F89-8257-92CBDD7DE29D</string>
</dict>
</plist>
