<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>wiki</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{{{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}}}</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>Google Code Wiki</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^#.*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^={1,6}[^=]*={1,6}$</string>
			<key>name</key>
			<string>markup.heading.googlecodewiki</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{{{</string>
			<key>end</key>
			<string>}}}</string>
			<key>name</key>
			<string>markup.raw</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\`[^`]*\`</string>
			<key>name</key>
			<string>markup.raw</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*[^*]*\*</string>
			<key>name</key>
			<string>markup.raw</string>
		</dict>
		<dict>
			<key>match</key>
			<string>_[^_]*_</string>
			<key>name</key>
			<string>markup.italic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\^[^^]*\^</string>
			<key>name</key>
			<string>markup.italic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>,,[^,]*,,</string>
			<key>name</key>
			<string>markup.italic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>~~[^~]*~~</string>
			<key>name</key>
			<string>markup.italic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[.*\]</string>
			<key>name</key>
			<string>markup.underline.link</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^----+$\n?</string>
			<key>name</key>
			<string>markup.raw</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s+\*.*\n?</string>
			<key>name</key>
			<string>markup.list.unnumbered</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s+#.*\n?</string>
			<key>name</key>
			<string>markup.list.numbered</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s+[^\s]+.*\n?</string>
			<key>name</key>
			<string>markup.quote</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\|\|</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.googlecodewiki</string>
	<key>uuid</key>
	<string>F50B61C5-3BBD-4247-9DFE-7DA094F35CA2</string>
</dict>
</plist>
