<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ini</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>Active4D Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.active4d-ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.active4d-ini</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.active4d-ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(`).*$\n?</string>
			<key>name</key>
			<string>comment.line.backtick.active4d-ini</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.active4d-ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\\\).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-backslash.continuation.active4d-ini</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.active4d-ini</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.active4d-ini</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"(?!"")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.active4d-ini</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.active4d-ini</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.active4d-ini</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(true|false|yes|no)\b</string>
			<key>name</key>
			<string>constant.language.boolean.active4d-ini</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.active4d-ini</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)((\b(use sessions|use session cookies|session var name|session timeout|session purge interval|session cookie path|session cookie name|session cookie domain|serve nonexecutables|script timeout|safe script dirs|safe doc dirs|root|refresh interval|receive timeout|platform charset|parameter mode|output encoding|output charset|max request size|log level|locale|lib extension|lib dirs|http error page|fusebox page|expires|executable extensions|error page|encrypted source|default page|content charset|client is web server|cache control|auto relate one|auto relate many|auto refresh libs|auto create vars|auto create sessions)\b)|(\&lt;default\&gt;|\&lt;web\&gt;|\&lt;4d volume\&gt;|\&lt;boot volume\&gt;))</string>
			<key>name</key>
			<string>support.constant.active4d-ini</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.active4d-ini</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.active4d-ini</string>
	<key>uuid</key>
	<string>BECA5580-F845-4715-889C-134DF4BF67C2</string>
</dict>
</plist>
