<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>treetop</string>
		<string>tt</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(?:grammar|rule)\b(?!.*\bend\s*$)|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*(?:end\b|\})</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>Treetop</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.grammar.treetop</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.grammar.treetop</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(grammar)\s+([A-Za-z]\w*)</string>
			<key>name</key>
			<string>meta.grammar.treetop</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.rule.treetop</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.treetop</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?=rule\b)(?&lt;=^|\s)(rule)\b\s+([a-zA-Z]\w+)</string>
			<key>name</key>
			<string>meta.function.rule.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bend\b</string>
			<key>name</key>
			<string>keyword.control.end.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>/</string>
			<key>name</key>
			<string>meta.function-call.ordered-choice.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z]\w*</string>
			<key>name</key>
			<string>variable.non-terminal.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"(\\.|[^"])*+"|'(\\.|[^'])*+'</string>
			<key>name</key>
			<string>string.literal.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[(\\.|[^\]])*+\]</string>
			<key>name</key>
			<string>string.regexp.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.+</string>
			<key>name</key>
			<string>comment.single-line.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\S)[*?+]</string>
			<key>name</key>
			<string>punctuation.quantifier.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[!&amp;](?=\S)</string>
			<key>name</key>
			<string>punctuation.predicate.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[()]</string>
			<key>name</key>
			<string>punctuation.grouping.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>constant.any-char.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s|^)[*?+]|[!&amp;](?=\s|$)</string>
			<key>name</key>
			<string>invalid.floating-punctuation.treetop</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ruby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ruby code inline</string>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ruby</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.ruby</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nest_curly</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>nest_curly</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.ruby</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nest_curly</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.treetop</string>
	<key>uuid</key>
	<string>4C3F0BD9-0F5A-4EB9-962C-1F8C78F039FE</string>
</dict>
</plist>
