<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mxml</string>
	</array>
	<key>firstLineMatch_disabled</key>
	<string>^\s*&lt;\?xml</string>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>MXML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?&lt;((?i:mx\:Script))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.mxml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=&lt;/(mx\:Script))&gt;(?:\s*\n)?</string>
			<key>name</key>
			<string>source.actionscript3.embedded.mxml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!&lt;/(?:mx\:Script))&gt;</string>
					<key>end</key>
					<string>&lt;/((?i:mx\:Script))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.actionscript3</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?&lt;((?i:mx\:Style))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.mxml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=&lt;/(mx\:Style))&gt;(?:\s*\n)?</string>
			<key>name</key>
			<string>source.css.embedded.mxml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!&lt;/(?:mx\:Style))&gt;</string>
					<key>end</key>
					<string>&lt;/((?i:mx\:Style))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.css</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>doublequotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.mxml</string>
		</dict>
		<key>singlequotedString</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.mxml</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mxml</string>
	<key>uuid</key>
	<string>0D356A66-D791-4A8F-B021-F485C9377AB6</string>
</dict>
</plist>
