<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>confluence</string>
	</array>
	<key>firstLineMatch</key>
	<string>confluence</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Confluence</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(^h[1-6]([&lt;&gt;=()]+)?)(\([^)]*\)|{[^}]*})*(\.)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.heading.confluence</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.confluence</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.heading.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>markup.heading.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^bq([&lt;&gt;=()]+)?)(\([^)]*\)|{[^}]*})*(\.)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.blockquote.confluence</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.confluence</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.blockquote.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>markup.quote.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^fn[0-9]+([&lt;&gt;=()]+)?)(\([^)]*\)|{[^}]*})*(\.)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.footnote.confluence</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.confluence</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.footnote.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>markup.other.footnote.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^table([&lt;&gt;=()]+)?)(\([^)]*\)|{[^}]*})*(\.)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.footnote.confluence</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.confluence</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.footnote.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>markup.other.table.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=\S)</string>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>meta.paragraph.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.paragraph.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.confluence</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.paragraph.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(^p([&lt;&gt;=()]+)?)(\([^)]*\)|{[^}]*})*(\.)</string>
					<key>name</key>
					<string>entity.name.section.paragraph.confluence</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Since html is valid in confluence include the html patterns</string>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>code-macro</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(code)(:?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.macro.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.seperator.macro.confluence</string>
						</dict>
					</dict>
					<key>end</key>
					<string>({)(code)(?=})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.macro.end.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.macro.confluence</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.macro.code.confluence</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>xml</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>constant.other.paramater.name.confluence</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?={code})</string>
							<key>name</key>
							<string>meta.macro.code.xml.confluence</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#macro-parameters</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>}</string>
									<key>contentName</key>
									<string>text.xml</string>
									<key>end</key>
									<string>(?={code})</string>
									<key>name</key>
									<string>meta.embedded.block.xml</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>text.xml</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>java</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>constant.other.paramater.name.confluence</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?={code})</string>
							<key>name</key>
							<string>meta.macro.code.java.confluence</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#macro-parameters</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>}</string>
									<key>contentName</key>
									<string>source.java</string>
									<key>end</key>
									<string>(?={code})</string>
									<key>name</key>
									<string>meta.embedded.block.java</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>source.java</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string></string>
							<key>end</key>
							<string>(?={code})</string>
							<key>name</key>
							<string>meta.macro.code.content.confluence</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#macro-parameters</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>}</string>
									<key>contentName</key>
									<string>markup.raw.code.confluence</string>
									<key>end</key>
									<string>(?={code})</string>
									<key>name</key>
									<string>meta.macro.code.xml.content.confluence</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#macro</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>&amp; is handled automagically by confluence, so we match it to avoid text.html.basic from flagging it</string>
					<key>match</key>
					<string>&amp;(?![A-Za-z0-9]+;)</string>
					<key>name</key>
					<string>text.html.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\*+(\([^)]*\)|{[^}]*})*(\s+|$)</string>
					<key>name</key>
					<string>markup.list.unnumbered.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^#+(\([^)]*\)|{[^}]*})*\s+</string>
					<key>name</key>
					<string>markup.list.numbered.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.title.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.other.reference.link.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
								"								# Start name, etc
									(?:							# Attributes
										# I swear, this is how the language is defined,
										# couldnt make it up if I tried.
										(?:\([^)]+\))?(?:\{[^}]+\})?(?:\[[^\]]+\])?
											# Class, Style, Lang
									  | (?:\{[^}]+\})?(?:\[[^\]]+\])?(?:\([^)]+\))?
											# Style, Lang, Class
									  | (?:\[[^\]]+\])?(?:\{[^}]+\})?(?:\([^)]+\))?
											# Lang, Style, Class
									)?
									([^"]+?)					# Link name
									\s?							# Optional whitespace
									(?:\(([^)]+?)\))?
								":								# End name
								(\w[-\w_]*)						# Linkref
								(?=[^\w\/;]*?(&lt;|\s|$))			# Catch closing punctuation
																#  and end of meta.link
					</string>
					<key>name</key>
					<string>meta.link.reference.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.address.begin.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separatory.link.title.confluence</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.confluence</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.address.end.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)(?:([^|]*?)(\|))?(.*?)(\])</string>
					<key>name</key>
					<string>meta.link.confluence</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
						( (https?|s?ftp|ftps|file|smb|afp|nfs|(x-)?man|gopher|txmt)://|mailto:)
						[-:@a-zA-Z0-9_.,~%+/?=&amp;#]+(?&lt;![.,?:])
					</string>
					<key>name</key>
					<string>markup.underline.link.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.image.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.confluence</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
								\!										# Open image
								(\&lt;|\=|\&gt;)?								# Optional alignment
								(?:										# Attributes
									# I swear, this is how the language is defined,
									# couldnt make it up if I tried.
									(?:\([^)]+\))?(?:\{[^}]+\})?(?:\[[^\]]+\])?
										# Class, Style, Lang
								  | (?:\{[^}]+\})?(?:\[[^\]]+\])?(?:\([^)]+\))?
										# Style, Lang, Class
								  | (?:\[[^\]]+\])?(?:\{[^}]+\})?(?:\([^)]+\))?
										# Lang, Style, Class
								)?
								(?:\.[ ])?            					# Optional
								([^\s(!]+?)         					# Image URL
								\s?                						# Optional space
								(?:\(((?:[^\(\)]|\([^\)]+\))+?)\))?   	# Optional title
								\!										# Close image
								(?:
									:
									(\S*?(?:\w|\/|;))					# URL
									(?=[^\w\/;]*?(&lt;|\s|$))				# Catch closing punctuation
								)?
					</string>
					<key>name</key>
					<string>meta.image.inline.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\|(\([^)]*\)|{[^}]*})*(\\\||.)+\|</string>
					<key>name</key>
					<string>markup.other.table.cell.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\B(\*\*?)((\([^)]*\)|{[^}]*}|\[[^]]+\]){0,3})(\S.*?\S|\S)\1\B</string>
					<key>name</key>
					<string>markup.bold.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.begin.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.end.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>({{).*?(}})</string>
					<key>name</key>
					<string>markup.raw.confluence</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{quote}</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.quote.confluence</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.quote.confluence</string>
					<key>end</key>
					<string>{quote}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.quote.confluence</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.quote.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\B-((\([^)]*\)|{[^}]*}|\[[^]]+\]){0,3})(\S.*?\S|\S)-\B</string>
					<key>name</key>
					<string>markup.deleted.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\B\+((\([^)]*\)|{[^}]*}|\[[^]]+\]){0,3})(\S.*?\S|\S)\+\B</string>
					<key>name</key>
					<string>markup.underline.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:\b|\s)_((\([^)]*\)|{[^}]*}|\[[^]]+\]){0,3})(\S.*?\S|\S)_(?:\b|\s)</string>
					<key>name</key>
					<string>markup.italic.confluence</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\B([@\^~%]|\?\?)((\([^)]*\)|{[^}]*}|\[[^]]+\]){0,3})(\S.*?\S|\S)\1</string>
					<key>name</key>
					<string>markup.italic.phrasemodifiers.confluence</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Footnotes</string>
					<key>match</key>
					<string>(?&lt;!w)\[[0-9+]\]</string>
					<key>name</key>
					<string>entity.name.tag.confluence</string>
				</dict>
			</array>
		</dict>
		<key>macro</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>({)(?=\w)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.macro.begin.confluence</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.macro.end.confluence</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.macro.confluence</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#specific-macros</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)(:?)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.macro.confluence</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.seperator.macro.confluence</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#macro-parameters</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>macro-parameter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\w+)(?:(=)?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.paramater.name.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.seperator.argument.confluence</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>variable.parameter.macro.confluence</string>
					<key>end</key>
					<string>(?=}|\|)</string>
					<key>name</key>
					<string>meta.macro.parameter.confluence</string>
				</dict>
			</array>
		</dict>
		<key>macro-parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>punctuation.seperator.macro.parameter.confluence</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro-parameter</string>
				</dict>
			</array>
		</dict>
		<key>specific-macros</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code-macro</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.confluence</string>
	<key>uuid</key>
	<string>2D045A75-E4D7-4904-8766-D6234F10FCA1</string>
</dict>
</plist>
